<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <AssemblyName>BARControllerBridge</AssemblyName>
    <RootNamespace>BARControllerBridge</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile Condition="'$(RuntimeIdentifier)' != ''">true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract Condition="'$(RuntimeIdentifier)' != ''">true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Launcher\**\*.cs" />
    <Compile Remove="Installer\**\*.cs" />
    <Compile Remove="Restore\**\*.cs" />
    <Compile Remove="Shared\**\*.cs" />
  </ItemGroup>
</Project>
