<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <AssemblyName>BAR_Controller_Companion_Restore_v0.5.1</AssemblyName>
    <RootNamespace>BARControllerCompanionRestore</RootNamespace>
    <Version>0.5.1</Version>
    <AssemblyVersion>0.5.1.0</AssemblyVersion>
    <FileVersion>0.5.1.0</FileVersion>
    <InformationalVersion>0.5.1</InformationalVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishSingleFile Condition="'$(RuntimeIdentifier)' != ''">true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract Condition="'$(RuntimeIdentifier)' != ''">true</IncludeNativeLibrariesForSelfExtract>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Shared\*.cs" Link="Shared\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
