local root = assert(arg[1], "repository root argument required"):gsub("[\\/]$", "")
local function path(relative) return root .. "/" .. relative end
local function read(relative)
	local handle = assert(io.open(path(relative), "rb"), "missing file: " .. relative)
	local value = handle:read("*a"); handle:close(); return value
end
local checks = 0
local function expect(value, message)
	checks = checks + 1
	assert(value, string.format("validation %d failed: %s", checks, message))
end
local function contains(text, literal) return text:find(literal, 1, true) ~= nil end

local camera = read("luaui/Widgets/gui_controller_camera_test.lua")
expect(contains(camera, 'disassembleToggleHoldSeconds = 0.33'), "0.33 Disassemble default")
expect(contains(camera, 'disassembleToggleHoldSeconds = { 0.15, 1.50, 0.01'), "persisted slider range/step")
expect(contains(camera, 'label = "Disassemble Toggle Hold Duration"'), "Bindings UI label")
expect(contains(camera, 'nativeBarUIIntegration = "Native Experimental"'), "native setting default")
expect(contains(camera, 'options = { "Native Experimental", "Legacy Controller UI" }'), "native/legacy choices")
expect(contains(camera, 'options = { "Auto", "Xbox", "PlayStation" }'), "glyph style choices")
expect(contains(camera, 'spSelectUnitArray, { unitID }, false'), "A/RT+A direct exact selection")
expect(contains(camera, 'pcall(spSelectUnitArray, finalSelection, false)'), "area selection uses engine authority directly")
expect(contains(camera, 'ControllerCameraTestCancelNativeTargeting()'), "native cancellation")
expect(contains(camera, 'ControllerCameraTestIssueNativeDisassembleMove()'), "X native Move")
expect(contains(camera, 'ControllerCameraTestIssueNativeDisassembleStop()'), "LB+B native Stop")
expect(contains(camera, "ControllerCameraTestStartNativeSameTypeReclaim"), "same-type reclaim binding")
expect(contains(camera, 'ControllerCameraTestBeginNativeReclaim("single"'), "single reclaim binding")
expect(contains(camera, 'ControllerCameraTestIssueNativeTarget(params, shape)'), "A/X confirms actual native command")
expect(contains(camera, 'ControllerCameraTestFeatureCommandID(target.targetID)'), "native feature command encoding")
expect(contains(camera, 'ControllerCameraTestRestoreDisassembleConstructors("Constructors restored")'), "B restores constructor selection")
expect(contains(camera, 'ControllerCameraTestRebuildNativeTacticalModel'), "native tactical adapter")
expect(contains(camera, 'ControllerCameraTestRebuildNativeTacticalModel'), "native tactical descriptors")
expect(contains(camera, 'WG.ordermenu.controllerActivate'), "native tactical activation")
expect(contains(camera, 'ControllerCameraTestUpdateRadialStickSelection()'), "v0.7 analog build navigation restored")
expect(contains(camera, 'WG.buildmenu.controllerActivate'), "native build activation")
expect(contains(camera, 'local delay = desired and 0.15 or 0.35'), "input hysteresis")

local smartSelect = read("native-overrides/99351e53d26f5e55fa007ca1e208b936f22bd3ab/luaui/Widgets/unit_smart_select.lua")
expect(contains(smartSelect, "controllerApplyUnits"), "SmartSelect application API")
expect(contains(smartSelect, "controllerSelectUnit"), "SmartSelect unit API")
expect(contains(smartSelect, "spGetUnitTeam(unitID) ~= myTeamID"), "enemy rejection")
expect(contains(smartSelect, "spGetUnitNoSelect(unitID)"), "invalid/no-select rejection")
expect(contains(smartSelect, "spSelectUnitArray(result)"), "engine selection authority")
expect(not contains(smartSelect, "Spring.GiveOrder"), "selection helper does not emit commands")

local reclaim = read("native-overrides/99351e53d26f5e55fa007ca1e208b936f22bd3ab/luaui/Widgets/unit_smart_area_reclaim.lua")
expect(contains(reclaim, "controllerBegin"), "native reclaim begin")
expect(contains(reclaim, "controllerUpdate"), "native reclaim radius update")
expect(contains(reclaim, "controllerConfirm"), "native reclaim confirm")
expect(contains(reclaim, "controllerCancel"), "native reclaim cancel")
expect(contains(reclaim, "mode == 'any'"), "future any-type entry")
expect(contains(reclaim, "params = { controllerTargeting.targetID }"), "one-target native encoding")
expect(contains(reclaim, "api.controllerIssueCommand(RECLAIM, params"), "selected reclaimers receive native command through Order Menu")
expect(contains(reclaim, "gl.DrawGroundCircle"), "shared widget controller radius")
expect(not contains(reclaim, "markedTargets"), "no parallel target set")

local orders = read("native-overrides/99351e53d26f5e55fa007ca1e208b936f22bd3ab/luaui/Widgets/gui_ordermenu.lua")
expect(contains(orders, "controllerGetCommands"), "native command model")
expect(contains(orders, "cmd.disabled == true"), "native command availability")
expect(contains(orders, "OrderMenuFirestate.nextCycledVirtualIndex"), "BAR firestate helper")
expect(contains(orders, "Spring.GetCmdDescIndex(cmd.id)"), "actual descriptor lookup")
expect(contains(orders, "button == 1, button == 3"), "left/right activation parity")

local build = read("native-overrides/99351e53d26f5e55fa007ca1e208b936f22bd3ab/luaui/Widgets/gui_buildmenu.lua")
expect(contains(build, "controllerGetItems"), "native build model")
expect(contains(build, "units.unitRestricted[unitDefID]"), "native build restrictions")
expect(contains(build, "units.unitMetalCost[unitDefID]"), "native metal costs")
expect(contains(build, "units.unitEnergyCost[unitDefID]"), "native energy costs")
expect(contains(build, "controllerMoveFocus"), "native focus navigation")
expect(contains(build, "controllerGetFocus"), "two-way build focus export")
expect(contains(build, "controllerSetRadialOpen"), "radial-scoped build focus")
expect(contains(build, "controllerInputActive and math_max(3, defaultColls - 1)"), "gamepad-first enlarged native grid")
expect(contains(build, "widget:ViewResize()"), "layout refresh only on stable mode transition")
expect(contains(build, "button == 1, button == 3"), "queue decrement right-click parity")
expect(contains(orders, "controllerGetFocus"), "two-way order focus export")
expect(contains(orders, "controllerActivateState"), "descriptor-owned state activation")

local runtime = read("luaui/Include/controller_ui_runtime.lua")
expect(contains(runtime, '"nativeBarUI", "nativeCommandActive"'), "hint signature native state")
expect(contains(runtime, "self.glyphs.SetStyle(context.controllerGlyphStyle, context.controllerGlyphFamily)"), "glyph style runtime")
expect(contains(runtime, "disassemble-native"), "native Disassemble hints")

local glyphs = assert(dofile(path("luaui/Include/controller_glyphs.lua")))
expect(glyphs.DetectFamily("Xbox Wireless Controller") == "Xbox", "Xbox detection")
expect(glyphs.DetectFamily("Sony DualSense Wireless Controller") == "PlayStation", "PlayStation detection")
expect(glyphs.DetectFamily("mystery pad") == "Unknown", "unknown detection")
expect(glyphs.SetStyle("Auto", "Unknown") == "Xbox", "Auto unknown fallback")
expect(glyphs.SetStyle("Auto", "PlayStation") == "PlayStation", "Auto PlayStation")
expect(glyphs.Resolve("A").label == "Cross button", "PlayStation face mapping")
expect(glyphs.SetStyle("Xbox", "PlayStation") == "Xbox", "manual Xbox override")
expect(glyphs.Resolve("A").label == "A button", "Xbox face mapping")
expect(glyphs.Resolve("totally custom binding").fallback == true, "unknown binding text fallback")

local deploy = read("tools/dev-scripts/Deploy_v0.8.0_Native_Test.ps1")
local restore = read("tools/dev-scripts/Restore_v0.8.0_Native_Test.ps1")
expect(contains(deploy, "Unknown loose vanilla override"), "unknown loose override refusal")
expect(contains(deploy, "BAR is running"), "BAR-running refusal")
expect(contains(deploy, "AllowUnknownBase"), "explicit development override")
expect(contains(deploy, "'Build menu' = 165; 'Grid menu' = 0"), "one authoritative native build panel")
expect(contains(deploy, "widgetConfigPostSha256"), "native build-menu config rollback record")
expect(contains(restore, "Restore target escaped BAR data"), "restore path confinement")
expect(contains(restore, "Installed file changed after deployment"), "post-deploy mutation refusal")
print(string.format("Controller Native UI Integration tests passed: %d validations.", checks))
