local root = (arg and arg[1]) or "."
local function read(path) local file = assert(io.open(path, "rb")); local value = file:read("*a"); file:close(); return value end
local function equal(actual, expected, label) if actual ~= expected then error(label .. ": expected " .. tostring(expected) .. ", got " .. tostring(actual), 2) end end
local function truthy(value, label) if not value then error(label .. ": expected true", 2) end end
local function contains(value, needle, label) truthy(value:find(needle, 1, true) ~= nil, label) end
local function excludes(value, needle, label) truthy(value:find(needle, 1, true) == nil, label) end

local behavior = dofile(root .. "/luaui/Include/controller_disassemble_behavior.lua")
local camera = read(root .. "/luaui/Widgets/gui_controller_camera_test.lua")
local runtime = read(root .. "/luaui/Include/controller_ui_runtime.lua")
local runtimeWidget = read(root .. "/luaui/Widgets/gui_controller_ui_runtime.lua")
local layout = read(root .. "/luaui/Widgets/gui_controller_ui_layout.lua")
local renderer = read(root .. "/luaui/Include/controller_ui_shared_renderers.lua")
local operations = read(root .. "/tools/controller-companion/Shared/ReleaseOperations.cs")
local defaults = read(root .. "/controller-ui/shipping-defaults.json")

local count = 0
local function test(label, callback)
	count = count + 1; local number = tonumber(label:match("^(%d+)")); equal(number, count, "numbered validation")
	local ok, message = pcall(callback); if not ok then error(label .. ": " .. tostring(message), 0) end
end

test("1 toggle hold is one second", function() equal(behavior.DISASSEMBLE_TOGGLE_HOLD_SECONDS, 1, "hold") end)
test("2 unused timeout is twenty seconds", function() equal(behavior.DISASSEMBLE_UNUSED_TIMEOUT_SECONDS, 20, "timeout") end)
test("3 area reclaim has a distinct hold", function() equal(behavior.AREA_RECLAIM_HOLD_SECONDS, 0.45, "hold") end)
test("4 area marking has a distinct hold", function() equal(behavior.AREA_MARK_HOLD_SECONDS, 0.38, "hold") end)
test("5 chord starts one charge", function() local event = behavior.UpdateToggleCharge(behavior.NewToggleCharge(), 2, true, true); equal(event, "charge-started", "event") end)
test("6 charge reports deterministic progress", function() local state = behavior.NewToggleCharge(); behavior.UpdateToggleCharge(state, 2, true, true); behavior.UpdateToggleCharge(state, 2.5, true, true); equal(state.progress, 0.5, "progress") end)
test("7 completed normal chord enables", function() local state = behavior.NewToggleCharge(); behavior.UpdateToggleCharge(state, 2, true, true); local event = behavior.UpdateToggleCharge(state, 3, true, true); equal(event, "enable", "event") end)
test("8 completion waits for full release", function() local state = behavior.NewToggleCharge(); behavior.UpdateToggleCharge(state, 2, true, true); behavior.UpdateToggleCharge(state, 3, true, true); truthy(state.waitingForRelease, "release latch") end)
test("9 full release clears the latch", function() local state = behavior.NewToggleCharge(); behavior.UpdateToggleCharge(state, 2, true, true); behavior.UpdateToggleCharge(state, 3, true, true); behavior.UpdateToggleCharge(state, 3.1, false, false); truthy(not state.waitingForRelease, "released") end)
test("10 partial chord release cancels", function() local state = behavior.NewToggleCharge(); behavior.UpdateToggleCharge(state, 2, true, true); local event = behavior.UpdateToggleCharge(state, 2.2, true, false); equal(event, "charge-cancelled", "cancel") end)
test("11 stick intent wins before toggle", function() local state = behavior.NewToggleCharge(); behavior.UpdateToggleCharge(state, 2, true, true); local event = behavior.UpdateToggleCharge(state, 2.2, true, true, "Air", false); equal(event, "open-filter", "filter") end)
test("12 active mode ignores stick intent", function() local state = behavior.NewToggleCharge(); behavior.UpdateToggleCharge(state, 2, true, true); local event = behavior.UpdateToggleCharge(state, 2.2, true, true, "Air", true); equal(event, "charging", "still charging") end)
test("13 completed active chord disables", function() local state = behavior.NewToggleCharge(); behavior.UpdateToggleCharge(state, 2, true, true); local event = behavior.UpdateToggleCharge(state, 3, true, true, nil, true); equal(event, "disable", "disable") end)
test("14 up selects Last Selected", function() equal(behavior.FilterFromStick(0, 1), "Last Selected", "up") end)
test("15 down selects Combat", function() equal(behavior.FilterFromStick(0, -1), "Combat", "down") end)
test("16 left selects Builders", function() equal(behavior.FilterFromStick(-1, 0), "Builders", "left") end)
test("17 right selects Air", function() equal(behavior.FilterFromStick(1, 0), "Air", "right") end)
test("18 neutral stick selects nothing", function() equal(behavior.FilterFromStick(0.1, 0.1), nil, "neutral") end)
test("19 filter state starts persisted", function() local state = behavior.NewFilterRadial("Air"); equal(state.candidate, "Air", "candidate") end)
test("20 opening captures the initial value", function() local state = behavior.OpenFilterRadial(behavior.NewFilterRadial("Combat"), "Builders"); equal(state.initialValue, "Builders", "initial") end)
test("21 neutral motion preserves the candidate", function() local state = behavior.OpenFilterRadial(behavior.NewFilterRadial("Combat"), "Combat", "Air"); behavior.LatchFilterCandidate(state, nil); equal(state.candidate, "Air", "latched") end)
test("22 friendly toggle adds deterministically", function() local result, action = behavior.ToggleSelection({ 4, 2 }, 3); equal(table.concat(result, ","), "2,3,4", "result"); equal(action, "added", "action") end)
test("23 friendly toggle removes without clearing others", function() local result, action = behavior.ToggleSelection({ 2, 3, 4 }, 3); equal(table.concat(result, ","), "2,4", "result"); equal(action, "removed", "action") end)
test("24 removing the last unit allows empty selection", function() local result = behavior.ToggleSelection({ 7 }, 7); equal(#result, 0, "empty") end)
test("25 marked toggle adds", function() local result, action = behavior.ToggleMarked({}, 9); truthy(result[9], "marked"); equal(action, "added", "action") end)
test("26 marked toggle removes", function() local result, action = behavior.ToggleMarked({ [9] = true }, 9); equal(result[9], nil, "removed"); equal(action, "removed", "action") end)
test("27 replacement area discards old marks", function() local result = behavior.MergeMarked({ [1] = true }, { 2, 3 }, false); truthy(not result[1] and result[2] and result[3], "replace") end)
test("28 additive area keeps old marks", function() local result = behavior.MergeMarked({ [1] = true }, { 2 }, true); truthy(result[1] and result[2], "additive") end)
test("29 marked types are resolved without name lists", function() local result = behavior.CollectMarkedTypes({ [4] = true, [7] = true }, function(id) return id % 2 end); truthy(result[0] and result[1], "types") end)
test("30 targets are sorted", function() equal(table.concat(behavior.OrderTargets({ 7, 2, 5 }), ","), "2,5,7", "order") end)
test("31 duplicate targets are removed", function() equal(table.concat(behavior.OrderTargets({ 2, 2, 1 }), ","), "1,2", "dedupe") end)
test("32 timeout does not fire early", function() truthy(not behavior.TimeoutExpired(0, 19.99, false), "early") end)
test("33 timeout fires at threshold", function() truthy(behavior.TimeoutExpired(0, 20, false), "threshold") end)
test("34 successful use prevents unused timeout", function() truthy(not behavior.TimeoutExpired(0, 30, true), "used") end)
test("35 camera includes the pure behavior module", function() contains(camera, "controller_disassemble_behavior.lua", "include") end)
test("36 camera exposes all three gameplay timings", function() contains(camera, "disassembleToggleHoldSeconds", "toggle"); contains(camera, "disassembleUnusedTimeoutSeconds", "timeout"); contains(camera, "areaReclaimHoldSeconds", "reclaim") end)
test("37 RT+A accepts only safe selectable units", function() contains(camera, "ControllerCameraTestIsSafeSelectableUnit", "safe target") end)
test("38 RT+A uses toggle semantics", function() contains(camera, "ControllerDisassembleBehavior.ToggleSelection", "toggle") end)
test("39 RT+A never replaces unrelated selection", function() contains(camera, "ControllerCameraTestSafeSelectionSnapshot", "snapshot") end)
test("40 RT+A can remove the final selected unit", function() local result = behavior.ToggleSelection({ 1 }, 1); equal(#result, 0, "empty selection") end)
test("41 shared chord calls one state transition", function() contains(camera, "ControllerDisassembleBehavior.UpdateToggleCharge(", "transition") end)
test("42 shared chord uses LB and RB actions", function() contains(camera, "local lbDown = ControllerCameraTestActionDown(\"pitchModifier\")", "LB"); contains(camera, "local rbDown = ControllerCameraTestActionDown(\"buildRadial\")", "RB") end)
test("43 stick chord opens the visible radial", function() contains(camera, "ControllerCameraTestOpenVisibleSelectionRadial(stickSector)", "open") end)
test("44 releasing RB confirms the filter", function() contains(camera, "ControllerCameraTestActionReleased(\"buildRadial\")", "release RB") end)
test("45 releasing LB first cancels the filter", function() contains(camera, "modifier released first", "LB cancel") end)
test("46 entering mode discovers reclaim capability", function() contains(camera, "ControllerCameraTestUnitHasReclaimCapability", "capability") end)
test("47 capability discovery uses command descriptors", function() contains(camera, "Spring.FindUnitCmdDesc", "descriptor"); contains(camera, "Spring.GetUnitCmdDescs", "descriptors") end)
test("48 mode exits if reclaimers become invalid", function() contains(camera, "Disassemble Mode Ended: No Reclaimers", "invalid exit") end)
test("49 mode restores the captured reclaimer selection", function() contains(camera, "pcall(spSelectUnitArray, valid, false)", "selection enforced") end)
test("50 area targeting uses engine radius queries", function() contains(camera, "Spring.GetUnitsInCylinder", "radius") end)
test("51 buildings are not excluded from targets", function() local segment = camera:match("function ControllerCameraTestCollectOwnedTargetsInRadius.-\nend"); excludes(segment, "canMove", "no mobility filter") end)
test("52 same-type filtering uses unitDef IDs", function() contains(camera, "typeFilter[unitDefID]", "type filter") end)
test("53 A tap marks one friendly target", function() contains(camera, "ControllerCameraTestMarkSingleTarget", "single mark") end)
test("54 A hold activates area marking", function() contains(camera, "mark.active = true", "area mark") end)
test("55 RT makes area marking additive", function() contains(camera, "mark.additive = ControllerCameraTestIsQueueModifierActive()", "additive") end)
test("56 non-additive single mark replaces the set", function() contains(camera, "state.markedTargets = { [unitID] = true }", "replace") end)
test("57 direct reclaim targets the captured reclaimers", function() contains(camera, "spGiveOrderToUnitArray, state.reclaimers", "captured reclaimers") end)
test("58 direct reclaim uses sorted targets", function() contains(camera, "ControllerDisassembleBehavior.OrderTargets(targets)", "sorted") end)
test("59 subsequent reclaim orders are queued", function() contains(camera, "index == 1 and {} or { \"shift\" }", "queue") end)
test("60 LB+A hold starts same-type area reclaim", function() contains(camera, "ControllerCameraTestStartAreaReclaim", "area reclaim") end)
test("61 A confirms area reclaim", function() contains(camera, "ControllerCameraTestActionPressed(\"select\") or ControllerCameraTestActionPressed(\"smartAction\")", "confirm") end)
test("62 X also confirms area reclaim", function() contains(camera, "ControllerCameraTestActionPressed(\"smartAction\")", "X confirm") end)
test("63 B cancels area reclaim", function() contains(camera, "area reclaim cancelled", "cancel") end)
test("64 LB+B stops captured reclaimers", function() contains(camera, "ControllerCameraTestStopDisassembleReclaimers()", "stop"); contains(camera, "spGiveOrderToUnitArray, state.reclaimers, stopID", "captured set") end)
test("65 successful reclaim records mode use", function() contains(camera, "state.successfulActivity", "activity") end)
test("66 lifecycle enforces unused timeout", function() contains(camera, "ControllerDisassembleBehavior.TimeoutExpired", "timeout") end)
test("67 target marks are pruned after death or transfer", function() contains(camera, "ControllerCameraTestPruneMarkedTargets", "prune") end)
test("68 marked targets receive visible outlines", function() contains(camera, "for unitID in pairs(disassemble.markedTargets", "outlines") end)
test("69 both modal areas draw radius circles", function() contains(camera, "disassemble.markArea.radius", "mark radius"); contains(camera, "reclaimArea.radius", "reclaim radius") end)
test("70 context snapshot exposes all Disassemble states", function() contains(camera, "disassembleAreaMarking", "mark context"); contains(camera, "disassembleAreaReclaim", "reclaim context"); contains(camera, "markedCount", "count") end)
test("71 charging has one progress overlay", function() contains(camera, "ControllerCameraTestDrawDisassembleCharge", "charge") end)
test("72 normal controller code no longer toggles authoring", function() excludes(camera, "ui.ToggleEditor()", "no editor chord") end)
test("73 production runtime widget is enabled", function() contains(runtimeWidget, "enabled = true", "runtime enabled") end)
test("74 authoring widget is disabled", function() contains(layout, "enabled = false", "authoring disabled") end)
test("75 production runtime never loads editor helpers", function() excludes(runtime, "controller_ui_editor_workspace", "workspace absent"); excludes(runtime, "controller_ui_editor_input", "input absent") end)
test("76 production settings API has no editor toggle", function() excludes(runtime, "ToggleEditor", "toggle absent") end)
test("77 runtime contains contextual Disassemble hints", function() contains(runtime, "disassemble-reclaim", "reclaim hint"); contains(runtime, "disassemble-exit", "exit hint") end)
test("78 charging suppresses every ordinary hint", function() contains(runtime, "if context.disassembleToggleCharge then self.alpha = 1; return end", "suppression") end)
test("79 runtime advertises RT+A add/remove", function() contains(runtime, "normal-selection-toggle", "selection toggle hint") end)
test("80 runtime advertises RB release confirmation", function() contains(runtime, "Release to Confirm", "confirm hint") end)
test("81 runtime preserves authoring metadata during migration", function() contains(runtime, "legacyAuthorData", "author data"); contains(runtime, "legacyEditorChrome", "chrome") end)
test("82 runtime retains legacy bindings-button migration", function() contains(runtime, "MigrateLegacyBindingsButton", "migration") end)
test("83 renderer uses controller-scoped stat icon paths", function() contains(renderer, "controller/stat-icons/metal.png", "metal"); contains(renderer, "controller/stat-icons/energy.png", "energy"); contains(renderer, "controller/stat-icons/health.png", "health") end)
test("84 renderer exposes a semantic health role", function() contains(renderer, "healthStat =", "role"); contains(defaults, "healthStatIconSize", "shipping role") end)
test("85 build radial has no internal footer prompt", function() excludes(renderer, "model.footer or model.subtitle or \"LS choose  A confirm\"", "footer removed"); excludes(camera, "ControllerCameraTestDrawBuildRadialPrompts", "legacy prompts removed") end)
test("86 resource shortage does not disable entries", function() excludes(camera, "disabled = not affordable", "not disabled") end)
test("87 engine-disabled descriptors remain disabled", function() contains(camera, "disabled = desc.disabled == true", "descriptor disabled") end)
test("88 selected expensive units show exact deficits", function() contains(camera, "NEED \" .. ControllerCameraTestFormatRadialStatNumber(deficitM) .. \" METAL", "metal deficit"); contains(camera, "ENERGY", "energy deficit") end)
test("89 installer enables runtime and disables layout", function() contains(operations, "\"Controller UI Runtime\"", "runtime order"); contains(operations, "DisabledWidgetNames", "layout disable") end)
test("90 installer copies the full legacy layout data block", function() contains(operations, "MigrateControllerUIRuntimeData", "migration"); contains(operations, "FindMatchingBrace(content, layoutOpen)", "balanced copy") end)

equal(count, 90, "validation count")
print("Controller Disassemble Mode tests passed: 90/90 numbered validations.")
