local root = assert(arg and arg[1], "repository root argument required"):gsub("\\", "/"):gsub("/$", "")
local function read(relative)
	local handle = assert(io.open(root .. "/" .. relative, "rb"), "missing " .. relative)
	local value = handle:read("*a"):gsub("\r\n", "\n")
	handle:close()
	return value
end
local function has(text, literal) return text:find(literal, 1, true) ~= nil end
local function lacks(text, literal) return not has(text, literal) end
local function all(text, ...)
	for _, literal in ipairs({ ... }) do if not has(text, literal) then return false end end
	return true
end
local function ordered(text, ...)
	local cursor = 1
	for _, literal in ipairs({ ... }) do
		local found = text:find(literal, cursor, true)
		if not found then return false end
		cursor = found + #literal
	end
	return true
end
local function section(text, first, last)
	local startIndex = assert(text:find(first, 1, true), first)
	local endIndex = assert(text:find(last, startIndex + #first, true), last)
	return text:sub(startIndex, endIndex - 1)
end

local camera = read("luaui/Widgets/gui_controller_camera_test.lua")
local runtime = read("luaui/Include/controller_ui_runtime.lua")
local layout = read("luaui/Widgets/gui_controller_ui_layout.lua")
local sharedRenderer = read("luaui/Include/controller_ui_shared_renderers.lua")
local nativeRenderer = read("luaui/Include/controller_native_build_cell_renderer.lua")
local disassembleBehavior = read("luaui/Include/controller_disassemble_behavior.lua")
local buildmenu = read("native-overrides/99351e53d26f5e55fa007ca1e208b936f22bd3ab/luaui/Widgets/gui_buildmenu.lua")
local defaults = read("controller-ui/shipping-defaults.json")
local defaultsManifest = read("controller-ui/shipping-defaults-manifest.json")
local props = read("tools/controller-companion/Directory.Build.props")
local companionTests = read("tools/controller-companion/Tests/Program.cs")
local releaseSpec = read("tools/release/controller-release-payloads.json")
local releaseBuilder = read("tools/release/Build-ControllerPublicRelease.ps1")
local releaseDeploy = read("tools/release/Deploy-ControllerPublicRelease.ps1")
local releaseSystem = read("tools/release/Test-ControllerReleaseSystem.ps1")
local releaseNotes = read("tools/release/bar-controller-support-v0.8.5/RELEASE_NOTES_v0.8.5.md")
local releaseReadme = read("tools/release/bar-controller-support-v0.8.5/README.md")
local liveChecklist = read("doc/controller-companion-v0.8.5/LIVE_TEST_CHECKLIST.md")

local insertContext = section(camera, "function ControllerCameraTestIsInsertModifierActive", "function ControllerCameraTestAppendQueueRemovalDebug")
local generalInsert = section(camera, "function ControllerCameraTestIsRBXGeneralInsertPressed", "function ControllerCameraTestRestoreDisassembleConstructors")
local nativeTargeting = section(camera, "function ControllerCameraTestIssueNativeTarget", "function ControllerCameraTestGetVisibleAlliedUnits")
local staged = section(camera, "function ControllerCameraTestHandleStagedTacticalCommandInput", "function ControllerCameraTestActivateNativeState")
local normalX = section(camera, "function ControllerCameraTestHandleNormalXInput", "function ControllerCameraTestHandleCommandLayerDragInputs")
local mainLoop = section(camera, "function ControllerCameraTestUpdateControllerModeAndCommandLayer", "function ControllerCameraTestApplyInputCurve")
local factoryHelpers = section(camera, "function ControllerCameraTestFactoryQueueEntryBuildCmdID", "local AFFORDABILITY_DISPLAY_SAMPLE_SECONDS")
local factoryInsert = section(camera, "function ControllerCameraTestDequeueFactoryBuildOption", "function ControllerCameraTestEnterPlacementFromHighlight")
local queueToggle = section(camera, "function ControllerCameraTestToggleFactoryQueueMode", "function ControllerCameraTestResolveLBLongAction")
local buildRadial = section(camera, "function ControllerCameraTestDrawBuildRadial", "function ControllerCameraTestFormatSettingsUIValue")
local idle = section(camera, "function ControllerCameraTestUnitIsIdle", "function ControllerCameraTestCycleIdleUnit")
local typeNav = section(camera, "function ControllerCameraTestIsMobileTypeNavigationCandidate", "function ControllerCameraTestCycleIdleUnit")
local disassembleEligibility = section(camera, "function ControllerCameraTestUnitHasReclaimCapability", "function ControllerCameraTestPruneMarkedTargets")
local areaReclaim = section(camera, "function ControllerCameraTestGetDisassembleAreaReclaimRadius", "function ControllerCameraTestUpdateDisassembleModeInput")
local context = section(camera, "function ControllerCameraTestGetContextSnapshot", "function ControllerCameraTestInstallWGAPI")
local cancelDrag = section(camera, "function ControllerCameraTestCancelDrag", "local function IsUnitInSelection")

local cases = {}
local function test(number, label, callback)
	assert(number == #cases + 1, "case numbering drift at " .. tostring(number))
	cases[#cases + 1] = { label = label, callback = callback }
end

test(1, "central version is v0.8.5 Experimental", function() return has(props, ">0.8.5<") and has(companionTests, "BAR Controller Bridge v0.8.5 Experimental") end)
test(2, "release spec uses v0.8.5 tag", function() return has(releaseSpec, "controller-support-v0.8.5-unit-insert-quota-type-navigation") end)
test(3, "release spec uses required asset name", function() return has(releaseSpec, "BAR_Controller_Support_v0.8.5_UNIT_INSERT_QUOTA_TYPE_NAVIGATION.zip") end)
test(4, "release title names quota and type navigation", function() return has(releaseSpec, "Unit Insert, Factory Quota & Type Navigation") end)
test(5, "release sequence advances", function() return has(releaseSpec, '"releaseSequence": 800500') end)
test(6, "builder defaults to v0.8.5 output", function() return has(releaseBuilder, "artifacts\\v0.8.5-public-release") and has(releaseBuilder, "Install_v0.8.5.ps1") end)
test(7, "public deploy backup uses v0.8.5", function() return has(releaseDeploy, "public-v0.8.5-") end)
test(8, "shipping defaults moved to v0.8.5", function() return all(defaults, "0.8.5-unit-insert-quota-type-navigation-1", "0.8.5-experimental") end)
test(9, "shipping manifest moved to v0.8.5", function() return all(defaultsManifest, '"minimumCompanionVersion": "0.8.5"', '"revision": 13') end)
test(10, "release docs identify package", function() return all(releaseNotes, "RB+X", "Queue/Quota Mode", "RB+D-pad") and all(releaseReadme, "v0.8.5", "RB+X") end)
test(11, "live checklist covers requested inputs", function() return all(liveChecklist, "RB+X", "RB+A", "RB+D-pad", "Self Destruct") end)

test(12, "general insert state exists", function() return has(camera, "ControllerCameraTestGeneralInsert = ControllerCameraTestGeneralInsert") end)
test(13, "queue-front is active for placement RB", function() return ordered(insertContext, "if ControllerCameraTestBuildPlacement.active == true then", "return ControllerCameraTestIsInsertModifierActive()") end)
test(14, "queue-front general path requires explicit insert window", function() return has(insertContext, "ControllerCameraTestGeneralInsert.active == true") end)
test(15, "RB alone no longer general-inserts active commands", function() return lacks(section(insertContext, "function ControllerCameraTestIsQueueFrontModifierActive", "function ControllerCameraTestIsFactoryInsertModifierActive"), "ControllerCameraTestIsCommandInsertContextActive()") end)
test(16, "RB+X detector requires RB and X", function() return all(generalInsert, 'ControllerCameraTestActionDown("buildRadial")', 'ControllerCameraTestActionPressed("smartAction")') end)
test(17, "RB+X detector excludes build/factory/disassemble modal contexts", function() return all(generalInsert, "not ControllerCameraTestBuildMenu.open", "not ControllerCameraTestBuildPlacement.active", "not ControllerCameraTestDisassemble.active") end)
test(18, "general insert helper consumes RB chord", function() return ordered(generalInsert, "state.active = true", 'ControllerCameraTestConsumeRBChord("RB+X general insert")', "state.active = false") end)
test(19, "general insert helper catches errors", function() return has(generalInsert, "pcall(issueFn)") and has(generalInsert, "insert error") end)
test(20, "active native command can be inserted directly", function() return all(generalInsert, "ControllerCameraTestConfirmNativeActiveCommand(cmdID)", '"native active command"') end)
test(21, "native target dispatch emits insert-front mode", function() return has(nativeTargeting, 'ControllerCameraTestIsQueueFrontModifierActive() and "insert-front" or nil') end)
test(22, "native target insert shows INSERT feedback", function() return ordered(nativeTargeting, 'dispatchMode == "insert-front"', 'ControllerCameraTestShowHotkeyFeedback("INSERT", "queue")') end)
test(23, "native target confirm wraps RB+X point dispatch", function() return ordered(nativeTargeting, "generalInsertPressed", 'ControllerCameraTestRunWithGeneralInsert("native target"', 'ControllerCameraTestIssueNativeTarget(params, "point")') end)
test(24, "native area anchor consumes RB+X without dispatch", function() return all(nativeTargeting, 'ControllerCameraTestConsumeRBChord("RB+X native anchor")', "native anchor armed by RB+X") end)
test(25, "staged tactical insert uses RB+X explicit path", function() return all(staged, "generalInsertPressed", 'ControllerCameraTestRunWithGeneralInsert("staged tactical"') end)
test(26, "staged area anchor consumes RB+X", function() return all(staged, 'ControllerCameraTestConsumeRBChord("RB+X staged anchor")', "staged anchor armed by RB+X") end)
test(27, "Smart X press arms general insert", function() return ordered(normalX, "local generalInsertPress", "drag.generalInsertPressActive = generalInsertPress == true", "Smart X insert armed") end)
test(28, "Smart X insert keeps flag during hold", function() return ordered(normalX, "ControllerCameraTestActionDown(\"smartAction\")", "drag.generalInsertPressActive", "ControllerCameraTestGeneralInsert.active = true") end)
test(29, "Smart X tap dispatches while insert flag is active", function() return ordered(normalX, "local generalInsertPress = drag.generalInsertPressActive == true", "ControllerCameraTestGeneralInsert.active = true", "attemptContextCommand(drag.smartPressTargetInfo)", "ControllerCameraTestGeneralInsert.active = false") end)
test(30, "cancelled drag clears insert flag", function() return all(cancelDrag, "drag.generalInsertPressActive = false", "ControllerCameraTestGeneralInsert.active = false") end)
test(31, "main loop checks RB+X before native targeting", function() return ordered(mainLoop, "ControllerCameraTestUpdateRBXGeneralInsert()", "ControllerCameraTestUpdateRBMobileTypeNavigation()", "ControllerCameraTestHandleNativeTargetingInput()") end)
test(32, "RB chord consumption owns release latch", function() return all(insertContext, "function ControllerCameraTestConsumeRBChord", "waitingForRBRelease = true", "ControllerCameraTestCancelVisibleSelectionRadial") end)
test(33, "RT+RB suppression reuses RB consumption helper", function() return ordered(insertContext, "RT+RB suppressed", "ControllerCameraTestConsumeRBChord(\"RT+RB suppression\")") end)

test(34, "factory queue parser recognizes normal build commands", function() return all(factoryHelpers, "cmdID and cmdID < 0", "math.max(1, math.floor(quantity))") end)
test(35, "factory queue parser recognizes inserted build commands", function() return all(factoryHelpers, "cmdID == tonumber(CMD.INSERT)", "local insertedCmdID = tonumber(params[2])", "insertedCmdID < 0") end)
test(36, "factory queue counts include parsed insert quantity", function() return has(factoryHelpers, "counts[buildCmdID] = (counts[buildCmdID] or 0) + (quantity or 1)") end)
test(37, "factory refresh updates counts and progress together", function() return ordered(factoryHelpers, "function ControllerCameraTestRefreshFactoryQueueModel", "ControllerCameraTestRefreshFactoryQueueCounts()", "ControllerCameraTestRefreshFactoryQueueProgress()") end)
test(38, "factory refresh invalidates native model while open", function() return all(factoryHelpers, "menu.nativeModel = nil", "buildModelRevision = -1") end)
test(39, "factory insert refreshes immediately", function() return has(factoryInsert, 'ControllerCameraTestRefreshFactoryQueueModel("factory insert")') end)
test(40, "native queue/dequeue refresh immediately", function() return all(camera, 'ControllerCameraTestRefreshFactoryQueueModel("native factory dequeue")', 'ControllerCameraTestRefreshFactoryQueueModel("native factory queue")') end)
test(41, "queue/quota detector reads ordermenu state", function() return all(factoryHelpers, "ControllerCameraTestDetectFactoryQuotaMode", "controllerGetCommands", "factoryqueuemode") end)
test(42, "factory mode toggle has exact toasts", function() return has(queueToggle, 'nextState == 0 and "Queue Mode" or "Quota Mode"') end)
test(43, "factory mode toggle stores quota mode", function() return has(queueToggle, "ControllerCameraTestBuildMenu.factoryQuotaModeActive = nextState ~= 0") end)
test(44, "quota info accepts exported quota text", function() return all(factoryHelpers, "option.quotaText", "string.match(option.quotaText") end)
test(45, "quota info can fall back to WG.Quotas", function() return all(factoryHelpers, "WG.Quotas", "getQuotas", "getUnitAmount") end)
test(46, "build radial detects quota mode", function() return has(buildRadial, "local quotaMode = isFactoryContext and ControllerCameraTestDetectFactoryQuotaMode()") end)
test(47, "build radial prefers parsed queue counts", function() return ordered(buildRadial, "local parsedQueueCount", "local queueCount = quotaMode and 0 or parsedQueueCount") end)
test(48, "build radial passes quota text to entries", function() return all(buildRadial, "quotaText = quotaInfo and quotaInfo.text or nil", "quotaDesired") end)
test(49, "build radial passes progress and quota to native cell", function() return all(buildRadial, "progress = entry.progress", "quotaText = entry.quotaText") end)
test(50, "shared radial model gets quota heading and center fill", function() return all(buildRadial, 'heading = quotaMode and "QUOTA MODE"', "centerFill = quotaMode and quotaCenterFill") end)
test(51, "legacy radial quota badge is magenta", function() return all(buildRadial, "badgeAccent = quotaMode and quotaAccent", "1.0, 0.50, 0.88") end)
test(52, "legacy center panel turns magenta in quota mode", function() return all(buildRadial, "quotaCenterFill", 'gl.Text("QUOTA MODE"') end)
test(53, "native renderer draws progress overlay", function() return all(nativeRenderer, "local progress = tonumber(args.progress)", "local remaining = math.max", "gl.Rect(ix1, iy2 - overlayHeight, ix2, iy2)") end)
test(54, "native renderer draws quota instead of queue", function() return all(nativeRenderer, "local quotaText = args.quotaText", "local queue = quotaText and 0", "\\255\\255\\130\\190") end)
test(55, "shared renderer draws quota badge", function() return all(sharedRenderer, "entry.quotaText", "1.0, 0.34, 0.82") end)
test(56, "shared renderer honors center fill and heading", function() return all(sharedRenderer, "model.centerFill", "model.centerAccent", "model.heading") end)
test(57, "native build menu passes quota text to renderer", function() return all(buildmenu, "quotaText = tostring(quotaCount) .. \"/\" .. tostring(quotaDesired)", "queueCount = quotaText and 0") end)
test(58, "native build menu exports quota fields", function() return all(buildmenu, "quotaCount = quotaCount", "quotaDesired = quotaDesired", "quotaText = quotaText") end)

test(59, "idle factories with queues are excluded", function() return all(idle, "ControllerCameraTestFactoryHasQueueOrProduction", "Spring.GetFactoryCommands", "Spring.GetUnitIsBuilding") end)
test(60, "idle candidate rejects queued factory", function() return ordered(idle, "isFactory and ControllerCameraTestFactoryHasQueueOrProduction", "return false") end)
test(61, "primary idle pool is builder factory commander only", function() return has(idle, 'local pool = (isBuilder or isFactory or ControllerCameraTestIsCommanderUnit(unitID)) and "primary" or nil') end)
test(62, "idle candidate no longer admits passive infrastructure", function() return lacks(idle, "isInfrastructure") end)
test(63, "secondary idle pool remains mobile non-builder", function() return all(idle, "isMobile and not isBuilder", 'pool = "secondary"') end)
test(64, "type navigation state exists", function() return has(camera, "ControllerCameraTestUnitTypeNavigation = ControllerCameraTestUnitTypeNavigation") end)
test(65, "type navigation excludes static and factory units", function() return all(typeNav, "unitDef.isFactory == true", "unitDef.isBuilding == true", "ControllerCameraTestIsMobileUnitDef") end)
test(66, "type navigation buckets by UnitDef", function() return all(typeNav, "bucketsByDef[unitDefID]", "bucket.units[#bucket.units + 1] = unitID") end)
test(67, "type navigation representative is deterministic", function() return all(typeNav, "bucket.representativeID = bucket.units[1]", "representativeRule = \"lowest-unit-id\"") end)
test(68, "type navigation sorts by representative unit ID", function() return has(typeNav, "tonumber(a.representativeID)") end)
test(69, "RB+D-pad cycles mobile type", function() return all(typeNav, 'WasButtonPressed("dpadLeft")', 'WasButtonPressed("dpadRight")', "ControllerCameraTestCycleMobileUnitType") end)
test(70, "RB+D-pad Down selects visible same type", function() return all(typeNav, 'WasButtonPressed("dpadDown")', "ControllerCameraTestSelectVisibleMobileUnitType") end)
test(71, "visible type selection uses visibility and screen tests", function() return all(typeNav, "Spring.GetVisibleUnits", "ControllerCameraTestUnitIsOnScreen(unitID)") end)
test(72, "type navigation consumes RB chord", function() return has(typeNav, 'ControllerCameraTestConsumeRBChord("RB+D-pad mobile type")') end)
test(73, "type navigation blocks modal contexts", function() return all(typeNav, "ControllerCameraTestBuildMenu.open", "ControllerCameraTestNativeTargetingIsActive()", "commandLayerActive") end)
test(74, "main loop cancels area selection for type navigation", function() return has(mainLoop, "cancelled by RB+D-pad type navigation") end)

test(75, "Disassemble radius default is 24", function() return has(camera, "disassembleAreaReclaimRadius = 24") and has(defaults, '"disassembleAreaReclaimRadius": 24') end)
test(76, "Disassemble radius clamps to 12", function() return has(camera, "disassembleAreaReclaimRadius = { 12, 1200 }") and has(disassembleBehavior, "MIN_TARGET_RADIUS = 12") end)
test(77, "Disassemble same-type starts from remembered compact radius", function() return all(areaReclaim, "ControllerCameraTestGetDisassembleAreaReclaimRadius()", "area.radius = ControllerCameraTestGetDisassembleAreaReclaimRadius()") end)
test(78, "Disassemble area target waits before radius recompute", function() return has(areaReclaim, "not area.waitingForNeutral") end)
test(79, "Disassemble area radius persists while resizing", function() return has(areaReclaim, "ControllerCameraTestSettings.disassembleAreaReclaimRadius = area.radius") end)
test(80, "Disassemble eligibility requires reclaim capability", function() return ordered(disassembleEligibility, "local operatorDef", "ControllerCameraTestUnitHasReclaimCapability(unitID)") end)
test(81, "Disassemble eligibility admits commander/builders only", function() return all(disassembleEligibility, "ControllerCameraTestIsCommanderUnit(unitID)", "ControllerCameraTestIsBuilderUnitDef(unitDef)") end)
test(82, "LB+RB Disassemble toggle uses eligibility helper", function() return has(camera, "ControllerCameraTestSelectionHasDisassembleOperator(selected)") end)
test(83, "context exposes canDisassemble", function() return has(context, "canDisassemble = canDisassemble") end)

test(84, "context exposes general insert availability", function() return all(context, "generalInsertAvailable", "commandCaps.canSmartAction") end)
test(85, "context exposes quota mode", function() return has(context, "factoryQuotaMode = ControllerCameraTestBuildMenu.factoryQuotaModeActive == true") end)
test(86, "context exposes mobile type availability", function() return has(context, "mobileTypeNavigationAvailable = mobileTypeNavigationAvailable") end)
test(87, "context exposes self destruct first modifier", function() return has(context, 'selfDestructFirstModifier = IsButtonDown("back")') end)
test(88, "runtime staged insert hint is RB+X", function() return has(runtime, 'id = "staged-insert-order", inputs = { "RB", "X" }') end)
test(89, "layout staged insert hint is RB+X", function() return has(layout, 'id = "staged-insert-order", inputs = { "RB", "X" }') end)
test(90, "runtime normal insert hint is RB+X", function() return has(runtime, 'id = "normal-insert-order", inputs = { "RB", "X" }') end)
test(91, "layout normal insert hint is RB+X", function() return has(layout, 'id = "normal-insert-order", inputs = { "RB", "X" }') end)
test(92, "factory insert hint remains RB+A through bindings", function() return has(runtime, "factory-insert-queue") and has(runtime, 'chordActions = { "insertNextCommandModifier", "radialSelect" }') end)
test(93, "placement insert hint remains RB+A through bindings", function() return has(runtime, "placement-insert-order") and has(runtime, 'chordActions = { "insertNextCommandModifier", "place" }') end)
test(94, "Disassemble hint only shows when eligible", function() return has(runtime, "normal(c) and c.canDisassemble") and has(layout, "isNormal(c) and c.canDisassemble") end)
test(95, "mobile type hints exist", function() return all(runtime, "normal-type-prev", "normal-type-next", "normal-type-visible") and all(layout, "normal-type-prev", "normal-type-next", "normal-type-visible") end)
test(96, "self destruct hint waits for Back/View", function() return all(runtime, "normal-self-destruct-hint", "selfDestructFirstModifier", "selfDestructEligible") end)
test(97, "visible filter confirm is RB in both registries", function() return has(runtime, 'visible-filter-confirm", inputs = { "RB" }') and has(layout, 'visible-filter-confirm", inputs = { "RB" }') end)
test(98, "runtime signatures include v0.8.5 context", function() return all(runtime, "generalInsertAvailable", "factoryQuotaMode", "mobileTypeNavigationAvailable", "selfDestructFirstModifier") end)
test(99, "layout signature includes v0.8.5 context", function() return all(layout, "generalInsertAvailable", "factoryQuotaMode", "mobileTypeNavigationAvailable", "selfDestructFirstModifier") end)
test(100, "release system runs v0.8.5 harness", function() return has(releaseSystem, "Test-ControllerV085UnitInsertQuotaTypeNavigation.lua") and has(releaseSystem, "CONTROLLER_RELEASE_TESTS=116/116") end)

assert(#cases == 100, "expected exactly 100 focused cases")
for index, item in ipairs(cases) do
	local ok, result = pcall(item.callback)
	assert(ok and result == true, string.format("case %d failed: %s%s", index, item.label, ok and "" or (" (" .. tostring(result) .. ")")))
end
print("Controller v0.8.5 unit insert/quota/type navigation tests passed: 100/100 cases.")
