local root = assert(arg and arg[1], "repository root argument required"):gsub("\\", "/"):gsub("/$", "")
local function read(relative)
	local handle = assert(io.open(root .. "/" .. relative, "rb"), "missing " .. relative)
	local value = handle:read("*a"):gsub("\r\n", "\n")
	handle:close()
	return value
end
local function has(text, literal) return text:find(literal, 1, true) ~= nil end
local function lacks(text, literal) return not has(text, literal) end
local function all(text, ...)
	for _, literal in ipairs({ ... }) do if not has(text, literal) then return false end end
	return true
end
local function ordered(text, ...)
	local cursor = 1
	for _, literal in ipairs({ ... }) do
		local found = text:find(literal, cursor, true)
		if not found then return false end
		cursor = found + #literal
	end
	return true
end
local function section(text, first, last)
	local startIndex = assert(text:find(first, 1, true), first)
	local endIndex = assert(text:find(last, startIndex + #first, true), last)
	return text:sub(startIndex, endIndex - 1)
end

local camera = read("luaui/Widgets/gui_controller_camera_test.lua")
local runtime = read("luaui/Include/controller_ui_runtime.lua")
local layout = read("luaui/Widgets/gui_controller_ui_layout.lua")
local renderer = read("luaui/Include/controller_ui_shared_renderers.lua")
local defaults = read("controller-ui/shipping-defaults.json")
local defaultsManifest = read("controller-ui/shipping-defaults-manifest.json")
local props = read("tools/controller-companion/Directory.Build.props")
local companionTests = read("tools/controller-companion/Tests/Program.cs")
local releaseSpec = read("tools/release/controller-release-payloads.json")
local releaseBuilder = read("tools/release/Build-ControllerPublicRelease.ps1")
local releaseSystem = read("tools/release/Test-ControllerReleaseSystem.ps1")
local deploy = read("tools/dev-scripts/Deploy_v0.8.0_Native_Test.ps1")
local packageScript = read("tools/dev-scripts/Build_v0.8.0_Native_Test_Package.ps1")
local publicDeploy = read("tools/release/Deploy-ControllerPublicRelease.ps1")
local releaseNotes = read("tools/release/bar-controller-support-v0.8.4/RELEASE_NOTES_v0.8.4.md")
local releaseReadme = read("tools/release/bar-controller-support-v0.8.4/README.md")
local releaseV083Readme = read("tools/release/bar-controller-support-v0.8.3/README.md")

local insertContext = section(camera, "function ControllerCameraTestIsInsertModifierActive", "function ControllerCameraTestAppendQueueRemovalDebug")
local rtRb = section(camera, "function ControllerCameraTestUpdateRTRBHardSuppression", "function ControllerCameraTestIsAppendQueueModifierActive")
local mainLoop = section(camera, "function ControllerCameraTestUpdateControllerModeAndCommandLayer", "function ControllerCameraTestApplyInputCurve")
local normalX = section(camera, "function ControllerCameraTestHandleNormalXInput", "function ControllerCameraTestHandleCommandLayerDragInputs")
local smartRepair = section(camera, "function ControllerCameraTestGetSmartRepairTarget", "function ControllerCameraTestSelectionHasReclaimer")
local smartEnemy = section(camera, "function ControllerCameraTestSelectionHasReclaimer", "function ControllerCameraTestSmartTargetPosition")
local contextCommand = section(camera, "local function attemptContextCommand", "local function attemptAttackCommand")
local idleCandidate = section(camera, "function ControllerCameraTestIsIdleCycleCandidate", "function ControllerCameraTestGetIdleCycleUnits")
local idleCycle = section(camera, "function ControllerCameraTestGetIdleCycleUnits", "function ControllerCameraTestUnitTypeName")
local idleControls = section(camera, "function ControllerCameraTestHandleNormalUtilityInput", "function ControllerCameraTestGetModeSummary")
local idleBuckets = section(camera, "function ControllerCameraTestGetIdleUnitTypeBuckets", "function ControllerCameraTestSelectRepresentativeFromIdleTypeBucket")
local idleSelectAll = section(camera, "function ControllerCameraTestSelectAllIdleUnitsInCurrentTypeBucket", "function ControllerCameraTestGetControlGroupDisplaySlot")
local disassembleHelpers = section(camera, "function ControllerCameraTestNativeDisassembleTargets", "function ControllerCameraTestCancelNativeDisassembleGesture")
local disassembleB = section(camera, "function ControllerCameraTestHandleDisassembleB", "function ControllerCameraTestStartNativeSameTypeReclaim")
local nativeDisassemble = section(camera, "function ControllerCameraTestUpdateNativeDisassembleInput", "function ControllerCameraTestSelectionsContainSameUnits")
local legacyDisassemble = section(camera, "function ControllerCameraTestUpdateDisassembleModeInput", "function ControllerCameraTestUpdateDisassembleLifecycle")
local normalA = section(camera, "function ControllerCameraTestHandleNormalAInput", "local function attemptBuildMenu")
local areaReclaim = section(camera, "function ControllerCameraTestStartNativeSameTypeReclaim", "function ControllerCameraTestUpdateDisassembleModeInput")
local areaTargeting = section(camera, "function ControllerCameraTestUpdateAreaReclaimTargeting", "function ControllerCameraTestUpdateDisassembleModeInput")
local collectRadius = section(camera, "function ControllerCameraTestCollectOwnedTargetsInRadius", "function ControllerCameraTestSyncDisassembleTargetHighlights")
local drawWorld = section(camera, "function widget:DrawWorld", "if ControllerCameraTestBuildPlacement.active")
local selfDestruct = section(camera, "function ControllerCameraTestEnsureSelfDestructCommand", "function ControllerCameraTestFeatureIsResurrectable")
local armSelfDestruct = section(camera, "function ControllerCameraTestArmProtectedSelfDestruct", "function ControllerCameraTestHandleSelfDestructChord")
local tacticalExec = section(camera, "function ControllerCameraTestExecuteTacticalCommand", "function ControllerCameraTestHandleTacticalMenuInput")

local cases = {}
local function test(number, label, callback)
	assert(number == #cases + 1, "case numbering drift at " .. tostring(number))
	cases[#cases + 1] = { label = label, callback = callback }
end

test(1, "insert modifier is RB", function() return has(camera, 'insertNextCommandModifier = "RB"') and lacks(camera, 'insertNextCommandModifier = "Y"') end)
test(2, "settings default binds RB insert", function() return has(camera, '{ action = "insertNextCommandModifier", label = "Insert Order Modifier", default = "RB"') end)
test(3, "insert context includes build placement", function() return has(insertContext, "ControllerCameraTestBuildPlacement.active == true") end)
test(4, "insert context includes staged tactical option", function() return has(insertContext, 'type(ControllerCameraTestTacticalMenu.stagedOption) == "table"') end)
test(5, "insert context includes active native command", function() return has(insertContext, "ControllerCameraTestGetNativeActiveCommandID() ~= nil") end)
test(6, "insert context includes native targeting phase", function() return has(insertContext, 'phase ~= nil and phase ~= "IDLE"') end)
test(7, "queue-front modifier requires context", function() return ordered(insertContext, "ControllerCameraTestIsInsertModifierActive()", "ControllerCameraTestIsCommandInsertContextActive()") end)
test(8, "general command insert remains outside factory", function() return has(camera, "ControllerCameraTestGiveInsertOrderToUnit") and has(camera, "useInsert = (options == nil or #options == 0)") end)
test(9, "factory insert remains RB plus A", function() return has(camera, "ControllerCameraTestIsFactoryInsertModifierActive()") and has(runtime, "factory-insert-queue") end)
test(10, "placement insert remains wired", function() return has(camera, "ControllerCameraTestPlaceBuildOption") and has(camera, "ControllerCameraTestGiveInsertOrderToUnit(unitID, 0") end)
test(11, "native command insert passes insert-front", function() return has(camera, 'ControllerCameraTestIsQueueFrontModifierActive() and "insert-front" or nil') end)
test(12, "active native targeting handler is present", function() return has(camera, "function ControllerCameraTestHandleNativeTargetingInput") end)
test(13, "RT+RB suppression runs before native targeting", function() return ordered(mainLoop, "ControllerCameraTestUpdateRTRBHardSuppression()", "ControllerCameraTestHandleNativeTargetingInput()") end)
test(14, "native targeting runs before tactical toggle", function() return ordered(mainLoop, "ControllerCameraTestHandleNativeTargetingInput()", "ControllerCameraTestHandlePriorityTacticalToggle()") end)
test(15, "native targeting runs before Disassemble", function() return ordered(mainLoop, "ControllerCameraTestHandleNativeTargetingInput()", "ControllerCameraTestUpdateDisassembleController(dt)") end)
test(16, "RT+RB reads append and radial buttons", function() return all(rtRb, 'ControllerCameraTestActionDown("appendQueueModifier")', 'ControllerCameraTestActionDown("buildRadial")') end)
test(17, "RT+RB consumes the chord", function() return has(rtRb, 'ControllerInputChords.Consume') and has(rtRb, '"RT+RB suppression"') end)
test(18, "RT+RB waits for RB release", function() return has(rtRb, "ControllerCameraTestTacticalToggleLatch.waitingForRBRelease = true") end)
test(19, "RT+RB clears visible selection radial", function() return has(rtRb, 'ControllerCameraTestCancelVisibleSelectionRadial("RT+RB suppression")') end)
test(20, "RT+RB rearms only after neutral", function() return ordered(rtRb, "if state.active then", "if not rtDown and not rbDown then", "rearmed after RT+RB neutral") end)

test(21, "Smart X repair still prefers damaged friendly units", function() return all(smartRepair, "ControllerCameraTestIsAlliedUnit(unitID)", "ControllerCameraTestUnitNeedsRepair(unitID)", "Repair") end)
test(22, "Smart X repair issues through selected units", function() return has(smartRepair, "ControllerCameraTestIssueOrderToSelectedUnits(repairID") end)
test(23, "enemy reclaim rejects allied targets", function() return has(smartEnemy, "ControllerCameraTestIsAlliedUnit(unitID)") and has(smartEnemy, "allied target") end)
test(24, "enemy reclaim validates live unit IDs", function() return all(smartEnemy, "Spring.ValidUnitID", "Spring.GetUnitIsDead", "dead unit") end)
test(25, "enemy reclaim requires UnitDef", function() return has(smartEnemy, 'return nil, "unknown unit"') end)
test(26, "enemy reclaim requires selected reclaimer", function() return has(smartEnemy, "ControllerCameraTestSelectionHasReclaimer()") and has(smartEnemy, "no selected reclaimer") end)
test(27, "enemy reclaim uses smart or CMD reclaim ID", function() return has(smartEnemy, "commandIDs and commandIDs.reclaim") and has(smartEnemy, "CMD.RECLAIM") end)
test(28, "enemy reclaim issues Reclaim order", function() return has(smartEnemy, '{ unitID }, "Reclaim", "unit " .. tostring(unitID)') end)
test(29, "enemy reclaim gives reclaim feedback", function() return has(smartEnemy, 'ControllerCameraTestShowHotkeyFeedback("RECLAIM", "reclaim")') end)
test(30, "Smart X priority is repair then enemy reclaim then native then legacy", function() return ordered(contextCommand, "ControllerCameraTestTryIssueSmartRepair", "ControllerCameraTestTryIssueSmartEnemyReclaim", "tryNativeSmartRepairReclaimExtension", "attemptLegacyContextCommand") end)
test(31, "Hold-X still owns movement before release Smart X", function() return ordered(normalX, "HOLD_SECONDS", 'drag.mode = "moveLine"', 'ControllerCameraTestActionReleased("smartAction")', "attemptContextCommand(drag.smartPressTargetInfo)") end)
test(32, "Y repair path is absent", function() return lacks(camera, "function ControllerCameraTestIsRepairModifierActive") and lacks(camera, "repairModifier") end)
test(33, "Y repair hints are absent", function() return lacks(runtime, "normal-repair") and lacks(layout, "normal-repair") and lacks(defaults, "repairModifier") end)
test(34, "enemy reclaim records Smart X debug source", function() return has(smartEnemy, 'smartActionSource = tostring(source or "Smart X enemy reclaim")') end)

test(35, "idle pool state defaults primary", function() return has(camera, 'currentPool = "primary"') end)
test(36, "idle candidates require finished units", function() return has(idleCandidate, "ControllerCameraTestUnitIsFinished(unitID)") end)
test(37, "idle candidates require no command queue", function() return has(idleCandidate, "ControllerCameraTestUnitIsIdle(unitID)") end)
test(38, "primary idle pool includes builders factories infrastructure", function() return all(idleCandidate, "isBuilder", "isFactory", "isInfrastructure", 'pool = (isBuilder or isFactory or isInfrastructure) and "primary"') end)
test(39, "secondary idle pool is mobile non-builder", function() return all(idleCandidate, "isMobile", "not isBuilder", 'pool = "secondary"') end)
test(40, "transported units are excluded from mobile idle pool", function() return has(idleCandidate, "Spring.GetUnitTransporter") end)
test(41, "idle units default to primary", function() return has(idleCycle, 'poolName = poolName == "secondary" and "secondary" or "primary"') end)
test(42, "idle cycle records current pool", function() return has(idleCycle, "ControllerCameraTestIdleCycle.currentPool = poolName") end)
test(43, "normal D-pad cycles primary idle build pool", function() return has(idleControls, "ControllerCameraTestCycleIdleUnit(-1)") and has(idleControls, "ControllerCameraTestCycleIdleUnit(1)") end)
test(44, "LB+D-pad cycles secondary idle mobile pool", function() return has(idleControls, 'ControllerCameraTestCycleIdleUnit(-1, "secondary")') and has(idleControls, 'ControllerCameraTestCycleIdleUnit(1, "secondary")') end)
test(45, "LB+D-pad Down selects all current idle type", function() return has(idleControls, "ControllerCameraTestSelectAllFocusedIdleType()") end)
test(46, "idle buckets inherit remembered pool", function() return has(idleBuckets, "ControllerCameraTestIdleCycle.currentPool == \"secondary\"") end)
test(47, "idle buckets store their source pool", function() return has(idleBuckets, "pool = poolName") end)
test(48, "select-all uses remembered pool", function() return has(idleSelectAll, 'local poolName = ControllerCameraTestIdleCycle.currentPool == "secondary" and "secondary" or "primary"') end)
test(49, "primary no-idle message is specific", function() return has(camera, "no idle build/infrastructure units") end)
test(50, "secondary no-idle message is specific", function() return has(camera, "no idle mobile units") end)
test(51, "idle hints name build and mobile pools", function() return has(camera, "D-pad L/R builders/factories/infrastructure") and has(runtime, "Previous Idle Mobile") end)

test(52, "Disassemble validity excludes constructors", function() return has(disassembleHelpers, "ControllerCameraTestConstructorSet()[unitID]") end)
test(53, "Disassemble validity excludes invalid and dead units", function() return all(disassembleHelpers, "Spring.ValidUnitID", "Spring.GetUnitIsDead") end)
test(54, "Disassemble split creates friendly and enemy lists", function() return all(disassembleHelpers, "local friendly, enemy, seen", "ControllerCameraTestIsOwnedUnit(unitID)", "enemy[#enemy + 1]") end)
test(55, "friendly Disassemble uses vanilla selection", function() return has(disassembleHelpers, "spSelectUnitArray") and has(disassembleHelpers, "ControllerCameraTestSelectDisassembleFriendlyTargets") end)
test(56, "enemy Disassemble uses marked target set", function() return has(disassembleHelpers, "ControllerCameraTestSetDisassembleEnemyTargets") and has(disassembleHelpers, "state.markedTargets = marked") end)
test(57, "additive friendly target collection merges selection", function() return all(disassembleHelpers, "currentFriendly", "friendlySet", "DisassembleMapToArray(friendlySet)") end)
test(58, "additive enemy target collection merges marked enemies", function() return all(disassembleHelpers, "enemySet", "GetMarkedDisassembleEnemyTargets", "state.markedTargets = enemySet") end)
test(59, "non-additive friendly target clears enemy custom set", function() return ordered(disassembleHelpers, "selected[1] = unitID", "state.markedTargets = {}") end)
test(60, "non-additive enemy target clears friendly vanilla selection", function() return ordered(disassembleHelpers, "state.markedTargets = { [unitID] = true }", "ControllerCameraTestSelectDisassembleFriendlyTargets({})") end)
test(61, "selected Disassemble collection combines friendly and enemy", function() return all(disassembleHelpers, "ControllerCameraTestGetDisassembleSelectedTargetCollection", "for _, unitID in ipairs(friendly)", "for _, unitID in ipairs(enemy)") end)
test(62, "owned targets are pruned from custom enemy marks", function() return has(camera, "function ControllerCameraTestPruneMarkedTargets") and has(camera, "not ControllerCameraTestIsOwnedUnit(unitID)") end)
test(63, "Disassemble A press sanitizes friendly vanilla selection", function() return all(normalA, "ControllerCameraTestSplitDisassembleTargets", "spSelectUnitArray, sanitized") end)
test(64, "Disassemble A tap uses native reclaim target", function() return has(normalA, "ControllerCameraTestGetReticleNativeReclaimTarget()") end)
test(65, "Disassemble A tap toggles split target", function() return has(normalA, "ControllerCameraTestToggleDisassembleTarget(targetID, area.additive)") end)
test(66, "empty non-additive Disassemble tap clears both stores", function() return ordered(normalA, "ControllerCameraTestDisassemble.markedTargets = {}", "ControllerCameraTestSelectDisassembleFriendlyTargets({})", "ControllerCameraTestSyncDisassembleTargetHighlights()") end)
test(67, "Disassemble brush scans area targets", function() return has(normalA, "ControllerCameraTestCollectOwnedTargetsInRadius") and has(normalA, "area.brushedUnits[unitID] = true") end)
test(68, "Disassemble brush applies mixed collection", function() return has(normalA, "ControllerCameraTestApplyDisassembleTargetCollection(finalSelection, area.additive)") end)
test(69, "Disassemble highlights only custom enemy targets", function() return has(collectRadius, "if not ControllerCameraTestIsOwnedUnit(unitID) then") end)
test(70, "Disassemble radius accepts friendly and enemy matches", function() return ordered(collectRadius, "unitTeam == myTeam and ControllerCameraTestIsDisassembleConstructor", "ControllerCameraTestIsValidDisassembleTarget(unitID)") end)
test(71, "Disassemble radius respects UnitDef filter", function() return has(collectRadius, "typeFilter[unitDefID] == true") end)
test(72, "DrawWorld prunes marked targets in native mode", function() return has(drawWorld, "ControllerCameraTestPruneMarkedTargets()") end)
test(73, "DrawWorld draws controller area reclaim circle", function() return has(drawWorld, "reclaimArea.active") and has(drawWorld, "gl.DrawGroundCircle(reclaimArea.x") end)
test(74, "DrawWorld only draws candidate rings for enemy custom targets", function() return ordered(drawWorld, "for _, unitID in ipairs(reclaimArea.candidates or {})", "if not ControllerCameraTestIsOwnedUnit(unitID) then") end)

test(75, "native LB+A captures target info on press", function() return has(nativeDisassemble, "targetInfo = targetInfo") end)
test(76, "native LB+A does not dispatch before hold decision", function() return ordered(nativeDisassemble, "state.lbA = { pressActive = true", "ControllerCameraTestStartNativeSameTypeReclaim", "if not state.lbA.holdFired then", "ControllerCameraTestIssueDisassembleSelectedReclaim") end)
test(77, "native LB+A tap reclaims selected collection", function() return has(nativeDisassemble, 'ControllerCameraTestIssueDisassembleSelectedReclaim(\n				"Native Disassemble LB+A"') end)
test(78, "legacy LB+A tap reclaims selected collection", function() return has(legacyDisassemble, 'ControllerCameraTestIssueDisassembleSelectedReclaim(\n				"Disassemble LB+A"') end)
test(79, "selected reclaim gets mixed collection", function() return has(camera, "ControllerCameraTestGetDisassembleSelectedTargetCollection()") end)
test(80, "selected reclaim issues full target collection", function() return ordered(camera, "if #targets > 0 then", "ControllerCameraTestIssueDisassembleReclaim(targets)") end)
test(81, "selected reclaim falls back one-shot only when empty", function() return ordered(camera, "if #targets > 0 then", "return false", "return ControllerCameraTestIssueDisassembleSingleReclaim") end)
test(82, "LB+A hold anchors same-type area", function() return all(areaReclaim, "area.active", "area.anchorUnitID", "area.unitDefID", "same-type area anchored") end)
test(83, "LB+A hold captures anchor world position", function() return all(areaReclaim, "spGetUnitPosition(targetID)", "area.x, area.y, area.z") end)
test(84, "LB+A hold waits for neutral before confirm", function() return has(areaReclaim, "area.confirmArmed, area.waitingForNeutral") and has(areaReclaim, "area.waitingForNeutral, area.confirmArmed = false, true") end)
test(85, "LB+A area resizes from cursor", function() return has(areaTargeting, "reticleWorldX - area.x") and has(areaTargeting, "area.radius = clamp") end)
test(86, "LB+A area collects matching candidates", function() return has(areaTargeting, "ControllerCameraTestCollectOwnedTargetsInRadius(area.x, area.z, area.radius, { [area.unitDefID] = true })") end)
test(87, "LB+A area confirms with A or X", function() return has(areaTargeting, 'ControllerCameraTestActionPressed("select") or ControllerCameraTestActionPressed("smartAction")') end)
test(88, "LB+A area B cancels without exit", function() return has(areaTargeting, "area reclaim cancelled") and lacks(areaTargeting, "ControllerCameraTestExitDisassembleMode") end)
test(89, "LB+A area confirm remains in Disassemble", function() return ordered(areaTargeting, "ControllerCameraTestIssueDisassembleReclaim(targets)", "ControllerCameraTestRestoreDisassembleConstructors") and lacks(areaTargeting, "double-B exit") end)

test(90, "B clears mod-owned target state first", function() return ordered(disassembleB, "ControllerCameraTestClearDisassembleModOwnedTargetState", "ControllerCameraTestUsesNativeBARUI()") end)
test(91, "B then clears friendly vanilla selection", function() return has(disassembleB, "ControllerCameraTestGetSelectedDisassembleFriendlyTargets()") and has(disassembleB, "friendly selection cleared") end)
test(92, "B reset blocks double-B after clear", function() return ordered(disassembleB, "if consumed then", "ControllerDisassembleBehavior.NewDoubleBTap()", "return true") end)
test(93, "double-B exit only happens after clear path", function() return ordered(disassembleB, "UpdateDoubleBTap", 'event == "exit"', "ControllerCameraTestExitDisassembleMode") end)
test(94, "LB+B stop outranks B clear", function() return ordered(nativeDisassemble, "LB+B Stop", "ControllerCameraTestIssueNativeDisassembleStop()", "return true", "ControllerCameraTestHandleDisassembleB()") end)
test(95, "L3+R3 clear queue stays in Disassemble", function() return ordered(nativeDisassemble, 'ControllerCameraTestIssueClearQueueCommand("disassemble")', "return true") end)

test(96, "self-destruct descriptor is controller-owned", function() return has(selfDestruct, 'descriptorSource = "controller-self-destruct"') end)
test(97, "self-destruct keeps red native presentation", function() return has(selfDestruct, 'colorProfile = "danger"') and has(renderer, 'entry.kind == "self_destruct"') end)
test(98, "Tactical self-destruct button calls the custom flow", function() return ordered(tacticalExec, 'option.kind == "self_destruct"', "ControllerCameraTestArmProtectedSelfDestruct()") end)
test(99, "custom self-destruct direct flow issues immediately", function() return ordered(armSelfDestruct, "ControllerCameraTestTacticalMenu.open = false", "ControllerCameraTestIssueSelfDestruct()") end)
test(100, "arming function no longer sets tacticalArmed true", function() return lacks(armSelfDestruct, "state.tacticalArmed = true") end)
test(101, "safety chord is standalone again", function() return has(selfDestruct, "local chordActive = chordButtonsDown == true") end)
test(102, "safety chord still requires Back and both stick clicks", function() return all(selfDestruct, 'IsButtonDown("back")', 'IsButtonDown("rightStickClick")', 'IsButtonDown("leftStickClick")') end)
test(103, "protected hold still dispatches once", function() return ordered(selfDestruct, "not state.attempted", "state.attempted = true", "ControllerCameraTestIssueSelfDestruct()") end)
test(104, "normal clear queue remains separate from self destruct", function() return has(nativeDisassemble, 'ControllerCameraTestIssueClearQueueCommand("disassemble")') and lacks(tacticalExec, "ControllerCameraTestIssueSelfDestruct()") end)

test(105, "companion version is v0.8.4 Experimental", function() return has(props, ">0.8.4<") and has(companionTests, "BAR Controller Bridge v0.8.4 Experimental") end)
test(106, "shipping defaults track v0.8.4", function() return has(defaults, "0.8.4-general-insert-disassemble-idle-1") and has(defaultsManifest, '"minimumCompanionVersion": "0.8.4"') end)
test(107, "release spec names v0.8.4 package", function() return has(releaseSpec, "controller-support-v0.8.4-general-insert-disassemble-idle") and has(releaseSpec, "BAR_Controller_Support_v0.8.4_GENERAL_INSERT_DISASSEMBLE_IDLE_EXPANSION.zip") end)
test(108, "public builder defaults to v0.8.4 output", function() return has(releaseBuilder, "artifacts\\v0.8.4-public-release") and has(releaseBuilder, "Install_v0.8.4.ps1") end)
test(109, "release system runs v0.8.4 harness", function() return has(releaseSystem, "Test-ControllerV084GeneralInsertDisassembleIdle.lua") and has(releaseSystem, "CONTROLLER_RELEASE_TESTS=116/116") end)
test(110, "dev deploy and package include v0.8.4 harness", function() return has(deploy, "Test-ControllerV084GeneralInsertDisassembleIdle.lua") and has(packageScript, "Test-ControllerV084GeneralInsertDisassembleIdle.lua") end)
test(111, "release notes document the three repair pillars", function() return all(releaseNotes, "General Insert", "Disassemble", "Idle") and all(releaseReadme, "v0.8.4", "General Insert") end)
test(112, "v0.8.3 remains recoverable", function() return has(releaseV083Readme, "v0.8.3") and has(releaseSystem, "v0.8.3 remains available") end)
test(113, "publication validation checks Latest", function() return has(releaseSystem, "GitHub publication validation passes") and has(publicDeploy, "public-v0.8.4") end)

assert(#cases == 113, "expected exactly 113 focused cases")
for index, item in ipairs(cases) do
	local ok, result = pcall(item.callback)
	assert(ok and result == true, string.format("case %d failed: %s%s", index, item.label, ok and "" or (" (" .. tostring(result) .. ")")))
end
print("Controller v0.8.4 general insert/disassemble/idle tests passed: 113/113 cases.")
