local root = assert(arg and arg[1], "repository root argument required"):gsub("\\", "/"):gsub("/$", "")
local function read(relative)
	local handle = assert(io.open(root .. "/" .. relative, "rb"), "missing " .. relative)
	local value = handle:read("*a"):gsub("\r\n", "\n")
	handle:close()
	return value
end
local function has(text, literal) return text:find(literal, 1, true) ~= nil end
local function lacks(text, literal) return not has(text, literal) end
local function ordered(text, ...)
	local cursor = 1
	for _, literal in ipairs({ ... }) do
		local found = text:find(literal, cursor, true)
		if not found then return false end
		cursor = found + #literal
	end
	return true
end
local function section(text, first, last)
	local a = assert(text:find(first, 1, true), first)
	local b = assert(text:find(last, a + #first, true), last)
	return text:sub(a, b - 1)
end

local camera = read("luaui/Widgets/gui_controller_camera_test.lua")
local runtime = read("luaui/Include/controller_ui_runtime.lua")
local layout = read("luaui/Widgets/gui_controller_ui_layout.lua")
local renderer = read("luaui/Include/controller_ui_shared_renderers.lua")
local bindings = read("luaui/Widgets/gui_controller_bindings_ui.lua")
local defaults = read("controller-ui/shipping-defaults.json")
local defaultsManifest = read("controller-ui/shipping-defaults-manifest.json")
local props = read("tools/controller-companion/Directory.Build.props")
local releaseSpec = read("tools/release/controller-release-payloads.json")
local releaseBuilder = read("tools/release/Build-ControllerPublicRelease.ps1")
local releaseSystem = read("tools/release/Test-ControllerReleaseSystem.ps1")
local deploy = read("tools/dev-scripts/Deploy_v0.8.0_Native_Test.ps1")
local packageScript = read("tools/dev-scripts/Build_v0.8.0_Native_Test_Package.ps1")
local companionTests = read("tools/controller-companion/Tests/Program.cs")
local updateService = read("tools/controller-companion/UpdateService.cs")
local publisher = read("tools/controller-ui-publisher/Program.cs")
local releaseV081Readme = read("tools/release/bar-controller-support-v0.8.1/README.md")

local normalX = section(camera, "function ControllerCameraTestHandleNormalXInput", "function ControllerCameraTestHandleCommandLayerDragInputs")
local normalA = section(camera, "function ControllerCameraTestHandleNormalAInput", "function ControllerCameraTestSetLayerAction")
local repairTarget = section(camera, "function ControllerCameraTestGetRepairModifierTarget", "function ControllerCameraTestTryIssueRepairModifier")
local commandLayer = section(camera, "function ControllerCameraTestHandleCommandLayerInput", "function ControllerCameraTestConsumeLBCycle")
local tacticalExec = section(camera, "function ControllerCameraTestExecuteTacticalCommand", "function ControllerCameraTestHandleTacticalMenuInput")
local tacticalInput = section(camera, "function ControllerCameraTestHandleTacticalMenuInput", "function ControllerCameraTestIssueGuardOrPatrol")
local factoryInsert = section(camera, "function ControllerCameraTestInsertFactoryBuildOption", "function ControllerCameraTestEnterPlacementFromHighlight")
local buildPlacement = section(camera, "function ControllerCameraTestPlaceBuildOption", "function ControllerCameraTestPlaceHighlightedBuildOption")
local disassembleX = section(camera, "function ControllerCameraTestHandleDisassembleXInput", "function ControllerCameraTestIssueNativeDisassembleStop")
local disassembleB = section(camera, "function ControllerCameraTestHandleDisassembleB", "function ControllerCameraTestStartNativeSameTypeReclaim")
local nativeDisassemble = section(camera, "function ControllerCameraTestUpdateNativeDisassembleInput", "function ControllerCameraTestSelectionsContainSameUnits")
local disassembleClear = section(camera, "function ControllerCameraTestDisassembleHasTableEntries", "function ControllerCameraTestEnterDisassembleMode")
local visibleSameType = section(camera, "function ControllerCameraTestCollectVisibleOwnedSameType", "function ControllerCameraTestSelectVisibleSameTypeUnderReticle")
local idleCycle = section(camera, "function ControllerCameraTestGetIdleCycleUnits", "function ControllerCameraTestUnitTypeName")
local idleBuckets = section(camera, "function ControllerCameraTestGetIdleUnitTypeBuckets", "function ControllerCameraTestSelectRepresentativeFromIdleTypeBucket")
local selfDestruct = section(camera, "function ControllerCameraTestFindSelfDestructCommandID", "function ControllerCameraTestFeatureIsResurrectable")

local cases = {}
local function test(number, label, callback)
	assert(number == #cases + 1, "case numbering drift at " .. tostring(number))
	cases[#cases + 1] = { label = label, callback = callback }
end

-- Y Repair modifier.
test(1, "Y is the repair modifier default", function() return has(camera, 'repairModifier = "Y"') end)
test(2, "repairModifier is a first-class binding", function() return has(camera, '{ action = "repairModifier"') and has(defaults, '"repairModifier"') end)
test(3, "repair modifier state has an authoritative helper", function() return has(camera, "function ControllerCameraTestIsRepairModifierActive()") end)
test(4, "repair target requires allied valid living unit", function() return has(repairTarget, "ControllerCameraTestIsAlliedUnit(unitID)") and has(repairTarget, "Spring.ValidUnitID") and has(repairTarget, "Spring.GetUnitIsDead") end)
test(5, "repair target uses real default command id", function() return has(camera, "local ok, _, defaultCmdID = pcall(Spring.GetDefaultCommand)") end)
test(6, "repair accepts damaged or unfinished units", function() return has(camera, "function ControllerCameraTestUnitNeedsRepair") and has(camera, "buildProgress < 1") end)
test(7, "repair orders dispatch through normal selected-unit order path", function() return has(camera, 'ControllerCameraTestIssueOrderToSelectedUnits(repairID') and has(camera, '"Repair"') end)
test(8, "Y+A repair precedes normal A press selection", function() return ordered(normalA, "ControllerCameraTestIsRepairModifierActive()", 'ControllerCameraTestTryIssueRepairModifier("Y+A")', 'ControllerCameraTestActionPressed("select")') end)
test(9, "invalid Y+A falls through to normal A", function() return has(normalA, 'and ControllerCameraTestTryIssueRepairModifier("Y+A") then') and has(normalA, "area.pressActive = true") end)
test(10, "Y+X repairs or falls through to Smart X", function() return ordered(normalX, 'ControllerCameraTestTryIssueRepairModifier("Y+X")', "attemptContextCommand()") end)
test(11, "Y+X does not preempt Hold-X before release", function() return ordered(normalX, "HOLD_SECONDS", "ControllerCameraTestActionReleased(\"smartAction\")", 'ControllerCameraTestTryIssueRepairModifier("Y+X")') end)
test(12, "repair modifier logs branch result without per-frame spam", function() return has(camera, "repairModifierResult = \"fallback\"") and has(camera, "repairModifierResult = \"issued \"") end)

-- Tactical state and wait behavior.
test(13, "Hold Position is classified as move_state_cycle", function() return has(camera, 'kind = "move_state_cycle"') and has(camera, "Move State") end)
test(14, "Move State A/X supports direction delta", function() return has(tacticalExec, "local direction = (tonumber(stateDelta) or 1) < 0 and -1 or 1") end)
test(15, "Move State cycles Hold/Maneuver/Roam", function() return has(tacticalExec, '[0] = "Hold Position"') and has(tacticalExec, '[1] = "Maneuver"') and has(tacticalExec, '[2] = "Roam"') end)
test(16, "Move State keeps Tactical open", function() return ordered(tacticalExec, 'option.kind == "move_state_cycle"', "ControllerCameraTestTacticalMenu.open = true") end)
test(17, "Move State refreshes native Tactical model", function() return has(tacticalExec, 'ControllerCameraTestRebuildNativeTacticalModel("move state cycled")') end)
test(18, "Fire State remains a non-closing state cycle", function() return ordered(tacticalExec, 'option.kind == "fire_state_cycle"', "ControllerCameraTestTacticalMenu.open = true") end)
test(19, "Wait is a direct non-closing toggle", function() return ordered(tacticalExec, 'option.kind == "wait_toggle"', 'ControllerCameraTestIssueOrderToSelectedUnits(cmdID, {}, "Wait"', "ControllerCameraTestTacticalMenu.open = true") end)
test(20, "Wait refreshes item state after toggle", function() return has(tacticalExec, 'ControllerCameraTestRebuildNativeTacticalModel("wait toggled")') end)
test(21, "Tactical X sends reverse state delta", function() return has(tacticalInput, 'local stateDelta = ControllerCameraTestActionPressed("radialQuick") and -1 or 1') end)
test(22, "native immediate branch excludes state/toggle families", function() return has(tacticalExec, 'option.kind ~= "wait_toggle"') and has(tacticalExec, 'option.kind ~= "move_state_cycle"') and has(tacticalExec, 'option.kind ~= "fire_state_cycle"') end)

-- Factory and general insert queue.
test(23, "factory insert modifier is LT", function() return has(camera, "function ControllerCameraTestIsFactoryInsertModifierActive()") and has(camera, "(normalizedLeftTrigger or 0) > 0.5") end)
test(24, "factory LT+A uses real CMD.INSERT", function() return has(factoryInsert, "CMD.INSERT") and has(factoryInsert, "{ 0, option.cmdID, 0 }") end)
test(25, "factory insert issues exactly one focused unit command", function() return has(factoryInsert, "issuedCount = issuedCount + 1") and lacks(factoryInsert, "shift") end)
test(26, "factory insert shows historical INSERT toast", function() return has(factoryInsert, 'ControllerCameraTestShowHotkeyFeedback("INSERT"') end)
test(27, "factory A append remains routed through normal queue path", function() return has(camera, '"Factory queue " .. tostring(option.name)') and has(camera, "controllerQueue") end)
test(28, "factory X removal remains present", function() return has(camera, "function ControllerCameraTestDequeueFactoryBuildOption") and has(camera, "Factory dequeue") end)
test(29, "factory RT+A +5 remains present", function() return has(runtime, "Queue +5 Modifier") and has(camera, "factoryQueueQuantity = (normalizedRightTrigger or 0) > 0.5 and 5 or 1") end)
test(30, "factory RT+X -5 remains present", function() return has(camera, 'optionsToIssue = { "right", "shift" }') end)
test(31, "factory hint advertises LT+A Insert Queue", function() return has(runtime, 'id = "factory-insert-queue"') and has(runtime, 'inputs = { "LT", "A" }') and has(layout, 'label = "Insert Queue"') end)
test(32, "RB is the general insert modifier default", function() return has(camera, 'insertNextCommandModifier = "RB"') and has(defaults, '"insertNextCommandModifier": "Insert order"') end)
test(33, "general insert is gated to active command contexts", function() return has(camera, "function ControllerCameraTestIsCommandInsertContextActive()") and has(camera, "ControllerCameraTestBuildPlacement.active == true") end)
test(34, "general RB+A wraps normal commands in CMD.INSERT", function() return has(camera, "local useInsert = not isBuild") and has(camera, "local insertParams = { 0, cmdID, 0 }") end)
test(35, "build placement RB+A uses CMD.INSERT with facing", function() return has(buildPlacement, "cmdInsert") and has(buildPlacement, "{ 0, option.cmdID, 0, x, y, z, facing }") end)
test(36, "insert wrapper preserves command params", function() return has(camera, "for i = 1, #params do") and has(camera, "insertParams[#insertParams + 1] = params[i]") end)
test(37, "general insert uses outer alt only", function() return has(camera, 'local finalOptsTable = useInsert and {"alt"}') and has(camera, 'pcall(spGiveOrderToUnit, unitID, cmdInsert, insertParams, { "alt" })') end)
test(38, "general insert shows INSERT toast", function() return has(camera, 'ControllerCameraTestShowHotkeyFeedback("INSERT", "queue")') end)
test(39, "RB+A Insert Order hint appears for placement", function() return has(runtime, 'id = "placement-insert-order"') and has(runtime, 'chordActions = { "insertNextCommandModifier", "place" }') end)
test(40, "RB+A Insert Order hint appears for staged commands", function() return has(runtime, 'id = "staged-insert-order"') and has(layout, 'id = "staged-insert-order"') end)

-- Removed reclaim binding and Disassemble controls.
test(41, "Back+D-pad Down reclaim branch is removed", function() return ordered(commandLayer, 'ControllerCameraTestActionPressed("commandDown")', "Layer+D-pad Down reserved") end)
test(42, "command-layer hints no longer advertise Reclaim", function() return lacks(runtime, 'bind("commandDown", "Reclaim"') and lacks(layout, 'bind("commandDown", "Reclaim", isCommandLayer') end)
test(43, "shared reclaim helper remains available", function() return has(camera, "function ControllerCameraTestIssueReclaimOrStop()") and has(camera, "shared reclaim helper") end)
test(44, "Disassemble X still reclaims captured targets", function() return has(disassembleX, "if pending.targetInfo then") and has(disassembleX, "ControllerCameraTestIssueDisassembleSingleReclaim(pending.targetInfo") end)
test(45, "Disassemble X over ground still moves", function() return has(disassembleX, "ControllerCameraTestIssueNativeDisassembleMove(pending.groundInfo)") end)
test(46, "Disassemble Hold-X still starts path/line Move", function() return has(disassembleX, "ControllerCameraTestStartSingleUnitPath") and has(disassembleX, 'drag.mode = "moveLine"') end)
test(47, "Disassemble B clears mod-owned target state", function() return has(disassembleB, "ControllerCameraTestClearDisassembleModOwnedTargetState") end)
test(48, "mod-owned clear sweeps marked and highlighted targets", function() return has(disassembleClear, "state.markedTargets, state.highlightedTargets = {}, {}") end)
test(49, "mod-owned clear sweeps same-type area state", function() return has(disassembleClear, "state.areaReclaim.anchorUnitID") and has(disassembleClear, "state.areaReclaim.candidates = {}") end)
test(50, "mod-owned clear sweeps pending X and LB+A", function() return has(disassembleClear, "state.lbA.pressActive") and has(disassembleClear, "state.pendingX = { pressActive = false") end)
test(51, "clear B resets double-B exit timing", function() return ordered(disassembleB, "ControllerCameraTestClearDisassembleModOwnedTargetState", "ControllerDisassembleBehavior.NewDoubleBTap()", "return true") end)
test(52, "clear-state double-B exit remains", function() return ordered(disassembleB, "UpdateDoubleBTap", 'event == "exit"', "double-B exit") end)
test(53, "L3+R3 Clear Queue outranks B", function() return ordered(nativeDisassemble, 'ControllerCameraTestActionDown("removeQueuedCommand")', "ControllerCameraTestIssueClearQueueCommand", "LB+B Stop") end)
test(54, "Disassemble Clear Queue restores cached constructors", function() return ordered(nativeDisassemble, "ControllerCameraTestRestoreDisassembleConstructors", "ControllerCameraTestIssueClearQueueCommand") end)
test(55, "LB+B Stop remains inside Disassemble", function() return has(nativeDisassemble, "ControllerCameraTestIssueNativeDisassembleStop()") and has(camera, "function ControllerCameraTestIssueNativeDisassembleStop()") end)

-- Double-tap A and v0.6 idle navigation.
test(56, "same-type collection enumerates own team authoritatively", function() return has(visibleSameType, "ControllerCameraTestGetOwnTeamUnits()") end)
test(57, "same-type collection is UnitDefID based", function() return has(visibleSameType, "candidateDefID == unitDefID") end)
test(58, "same-type collection filters visible units", function() return has(visibleSameType, "Spring.GetVisibleUnits") and has(visibleSameType, "visibleSet[unitID]") end)
test(59, "same-type collection filters on-screen units", function() return has(visibleSameType, "ControllerCameraTestUnitIsOnScreen(unitID)") end)
test(60, "same-type collection excludes enemies and teammates by own-team enumeration", function() return has(camera, "function ControllerCameraTestGetOwnTeamUnits") and has(camera, "Spring.GetMyTeamID") end)
test(61, "same-type collection does not use cursor proximity", function() return lacks(visibleSameType, "GetUnitsInCylinder") and lacks(visibleSameType, "radius") end)
test(62, "double-tap selects the collected same-type units", function() return has(camera, "ControllerCameraTestSelectVisibleSameTypeUnderReticle") and has(camera, 'ControllerCameraTestSelectUnits(units, "A double-tap visible same type")') end)
test(63, "single tap exact selection remains", function() return has(camera, "attemptReticleSelection(targetID)") and has(camera, "single exact unit") end)
test(64, "Hold-A area selection remains", function() return has(normalA, "Hold-A threshold crossed") and has(normalA, "area.active = true") end)
test(65, "RT+A selection toggle remains", function() return has(normalA, "area.additive = ControllerCameraTestIsQueueModifierActive()") end)
test(66, "ordinary idle navigation no longer depends on WG idle snapshot", function() return lacks(idleCycle, "WG.idlebuilders") and lacks(idleBuckets, "controllerGetLiveIdleEntries") end)
test(67, "idle cycle restores v0.6 own-team enumeration", function() return has(idleCycle, "ControllerCameraTestGetOwnTeamUnits()") and has(idleCycle, "ControllerCameraTestIsIdleCycleCandidate") end)
test(68, "idle cycle prefers builders and falls back to mobile idle units", function() return has(idleCycle, "local builders, fallback = {}, {}") and has(idleCycle, "(#builders > 0) and builders or fallback") end)
test(69, "idle cycle sorts and wraps", function() return has(idleCycle, "table.sort(units)") and has(camera, "((currentIndex - 1 + delta) % #units) + 1") end)
test(70, "idle D-pad right/left are wired", function() return has(camera, "ControllerCameraTestCycleIdleUnit(1)") and has(camera, "ControllerCameraTestCycleIdleUnit(-1)") end)
test(71, "idle camera focus/select path remains direct", function() return has(camera, 'ControllerCameraTestFocusAndSelectUnit(unitID, "Idle unit")') end)
test(72, "idle type buckets come from restored idle list", function() return has(idleBuckets, "for _, unitID in ipairs(ControllerCameraTestGetIdleCycleUnits())") end)
test(73, "LB+D-pad Down same-type idle selection remains separate", function() return has(camera, "ControllerCameraTestSelectAllFocusedIdleType") and has(camera, "ControllerCameraTestSelectAllIdleUnitsInCurrentTypeBucket") end)
test(74, "busy same-type idle units are excluded through idle candidate filter", function() return has(camera, "ControllerCameraTestUnitIsIdle(unitID)") and has(camera, "ControllerCameraTestIsIdleCycleCandidate") end)

-- Self Destruct and visual rendering.
test(75, "Self Destruct command is ensured in Tactical Utility", function() return has(selfDestruct, "ControllerCameraTestEnsureSelfDestructCommand") and has(selfDestruct, 'tacticalCategory = "utility"') end)
test(76, "Self Destruct is available for any selected unit/structure with command support", function() return has(selfDestruct, "local selectedUnits") and has(selfDestruct, "#selectedUnits == 0") end)
test(77, "Self Destruct activation enters protected arm flow", function() return ordered(tacticalExec, 'option.kind == "self_destruct"', "ControllerCameraTestArmProtectedSelfDestruct()", "if option.disabled then") end)
test(78, "protected flow uses Back/View + R3 + L3 chord", function() return has(selfDestruct, 'IsButtonDown("back")') and has(selfDestruct, 'IsButtonDown("rightStickClick")') and has(selfDestruct, 'IsButtonDown("leftStickClick")') end)
test(79, "protected flow enforces safety hold", function() return has(selfDestruct, "state.holdSeconds or 0.75") and has(selfDestruct, "not state.attempted") end)
test(80, "protected flow supports cancellation and expiry", function() return has(selfDestruct, "Self Destruct cancelled") and has(selfDestruct, "tactical arm expired") end)
test(81, "successful Self Destruct dispatch occurs once after hold", function() return has(selfDestruct, "state.attempted = true") and has(selfDestruct, "state.issued = ControllerCameraTestIssueSelfDestruct()") end)
test(82, "Tactical item itself does not issue raw Self Destruct", function() return lacks(tacticalExec, "ControllerCameraTestIssueSelfDestruct()") and has(tacticalExec, "ControllerCameraTestArmProtectedSelfDestruct()") end)
test(83, "Self Destruct uses shared Tactical renderer", function() return has(camera, "controllerDrawCommandButton(entry.cmdID") and has(camera, 'entry.kind == "self_destruct"') end)
test(84, "Self Destruct receives danger color profile", function() return has(selfDestruct, 'colorProfile = "danger"') end)
test(85, "danger renderer uses red vertical gradient", function() return has(renderer, "verticalGradientRect") and has(renderer, "danger = entry.colorProfile == \"danger\"") end)
test(86, "danger focus styling remains in standard button geometry", function() return has(renderer, "selected and values.selectedScale") and has(renderer, "danger and (selected and { 1.0, 0.36, 0.26") end)

-- Hints, input priority, and preserved visuals.
test(87, "Y+A Repair hint appears", function() return has(runtime, 'id = "normal-repair-a"') and has(runtime, 'chordActions = { "repairModifier", "select" }') end)
test(88, "Y+X Repair / Smart Action hint appears", function() return has(runtime, 'id = "normal-repair-x"') and has(runtime, 'Repair / Smart Action') end)
test(89, "removed reclaim hint stays absent", function() return lacks(runtime, 'Back + D-pad Down') and lacks(layout, 'Back + D-pad Down') end)
test(90, "capability-aware hint filtering remains", function() return has(runtime, "canRepairCommand") and has(runtime, "canSmartAction") and has(runtime, "canTacticalCommand") end)
test(91, "sector label visual fixes remain", function() return has(renderer, "sector.labelColor or sector.accent or accent") and has(renderer, "0, 0, 0, 0.72 * opacity") end)
test(92, "affordability display smoothing remains", function() return has(camera, "AFFORDABILITY_DISPLAY_SAMPLE_SECONDS = 1.0") and has(camera, "AFFORDABILITY_DISPLAY_ALPHA = 0.35") end)
test(93, "input B priority is LB+B, target clear, then double-B", function() return ordered(nativeDisassemble, "LB+B Stop", "ControllerCameraTestHandleDisassembleB()") and ordered(disassembleB, "ControllerCameraTestClearDisassembleModOwnedTargetState", "UpdateDoubleBTap") end)
test(94, "stick-click priority is Clear Queue before independent clicks", function() return ordered(nativeDisassemble, "ControllerCameraTestIssueClearQueueCommand", "ControllerCameraTestHandleDisassembleB") end)
test(95, "shoulder priorities preserve RB page traversal elsewhere", function() return has(camera, "ControllerCameraTestTraverseRadialPages(1)") and has(camera, 'event == "rb-tap"') end)
test(96, "Distributed Grid priority remains guarded", function() return has(camera, "ControllerCameraTestUpdateDistributedGridChord") and has(camera, "distributedPlacementOwns") end)
test(97, "no controller gesture should duplicate factory insert append", function() return ordered(camera, "ControllerCameraTestIsFactoryInsertModifierActive()", "ControllerCameraTestInsertFactoryBuildOption(option)", "return true") end)
test(98, "insert action is known to companion validator", function() return has(updateService, '"repairModifier"') and has(publisher, '"repairModifier"') end)
test(99, "bindings UI explains repair and insert separately", function() return has(bindings, "repairModifier = \"Hold to make A or X issue Repair") and has(bindings, "insertNextCommandModifier = \"Hold to insert the next compatible order") end)
test(100, "layout editor knows repair modifier", function() return has(layout, 'repairModifier = "Commands"') and has(layout, '"repairModifier", "insertNextCommandModifier"') end)
test(101, "runtime knows repair modifier", function() return has(runtime, 'repairModifier = "Commands"') end)

-- Release and delivery metadata.
test(102, "central companion version is v0.8.2 Experimental", function() return has(props, ">0.8.2<") and has(companionTests, "v0.8.2 Experimental") end)
test(103, "bridge banner expects v0.8.2", function() return has(companionTests, "BAR Controller Bridge v0.8.2 Experimental") end)
test(104, "release spec names v0.8.2 tag", function() return has(releaseSpec, "controller-support-v0.8.2-tactical-insert-idle-repair") end)
test(105, "release spec names v0.8.2 package asset", function() return has(releaseSpec, "BAR_Controller_Support_v0.8.2_TACTICAL_INSERT_IDLE_REPAIR.zip") end)
test(106, "release title is v0.8.2 Tactical, Insert & Idle Repair", function() return has(releaseSpec, "BAR Controller Support v0.8.2") and has(releaseSpec, "Tactical, Insert & Idle Repair") end)
test(107, "shipping defaults target v0.8.2", function() return has(defaults, "0.8.2-tactical-insert-idle-repair") and has(defaults, "0.8.2-experimental") end)
test(108, "defaults manifest target v0.8.2", function() return has(defaultsManifest, "0.8.2-tactical-insert-idle-repair") and has(defaultsManifest, '"minimumCompanionVersion": "0.8.2"') end)
test(109, "public release builder emits v0.8.2 paths", function() return has(releaseBuilder, "v0.8.2-public-release") and has(releaseBuilder, "Install_v0.8.2.ps1") end)
test(110, "deployment backup root is v0.8.2", function() return has(deploy, "v0.8.2-tactical-insert-idle-repair-test") or has(read("tools/release/Deploy-ControllerPublicRelease.ps1"), "public-v0.8.2") end)
test(111, "dev package emits the v0.8.2 test package", function() return has(packageScript, "v0.8.2-tactical-insert-idle-repair-test") and has(packageScript, "TACTICAL_INSERT_IDLE_REPAIR_TEST") end)
test(112, "release system expects v0.8.2 latest", function() return has(releaseSystem, "controller-support-v0.8.2-tactical-insert-idle-repair") and has(releaseSystem, "bridge version remains v0.8.2 Experimental") end)
test(113, "v0.8.1 remains available for recovery in tests", function() return has(releaseV081Readme, "v0.8.1") and has(releaseSystem, "v0.8.1 remains available") end)
test(114, "v0.8.2 harness is included in dev package", function() return has(packageScript, "Test-ControllerV082TacticalInsertIdleRepair.lua") end)
test(115, "v0.8.2 harness is included in dev deploy validation", function() return has(deploy, "Test-ControllerV082TacticalInsertIdleRepair.lua") end)
test(116, "release system runs v0.8.2 harness", function() return has(releaseSystem, "Test-ControllerV082TacticalInsertIdleRepair.lua") end)
test(117, "all changed Lua files have parse coverage entry", function() return has(releaseSystem, "all changed Lua files parse") end)
test(118, "upvalue ceiling validation remains present", function() return has(releaseSystem, "upvalue") and has(releaseSystem, "60") end)
test(119, ".NET validation remains part of release system", function() return has(releaseSystem, "dotnet") or has(releaseSystem, ".NET") end)
test(120, "rollback validation remains part of release system", function() return has(releaseSystem, "rollback") or has(releaseSystem, "Rollback") end)
test(121, "package validation remains part of release system", function() return has(releaseSystem, "package") and has(releaseSystem, "hash") end)
test(122, "GitHub publication validation remains part of release system", function() return has(releaseSystem, "GitHub") or has(releaseSystem, "gh release") end)
test(123, "BAR remains closed by scripts", function() return has(releaseBuilder, "never launches BAR") or has(deploy, "BAR was not launched") end)

for index, item in ipairs(cases) do
	local ok, result = pcall(item.callback)
	assert(ok and result == true, string.format("case %d failed: %s%s", index, item.label, ok and "" or (" (" .. tostring(result) .. ")")))
end
print("Controller v0.8.2 tactical/insert/idle repair tests passed: 123/123 cases.")
